// EL Build Simulator app - generated by gen_el_sim3.py, do not edit by hand.
// Runs only after el-sim.html has fetched the gated payload into window.__EL_DATA.
(function(){

const D = window.__EL_DATA;
const [X0,X1,Y0,Y1] = D.crop;
const W = X1-X0+1, H = Y1-Y0+1;
const TW = 14, TH = 10.125;
const idx = (x,y)=> (y-Y0)*W + (x-X0);
const inCrop = (x,y)=> x>=X0&&x<=X1&&y>=Y0&&y<=Y1;
const uv = (x,y)=> [(x+y)/2,(x-y)/2];
const xy = (u,v)=> [u+v,u-v];
const N = W*H;

const ICONS_SRC = {"ps": "assets/el-sim/icon-ps.png?a=b53cd0a8", "fort": "assets/el-sim/icon-fort.png?a=8192c5d6", "outpost": "assets/el-sim/icon-outpost.png?a=f221094a", "base": "assets/el-sim/icon-base.png?a=0385f375", "gate": "assets/el-sim/icon-gate.png?a=7c2cb2fd", "mfort": "assets/el-sim/icon-mfort.png?a=f52afe38", "ark": "assets/el-sim/icon-ark.png?a=d1063a9e", "research": "assets/el-sim/icon-research.png?a=87e07768", "city": "assets/el-sim/icon-city.png?a=5019e1b3", "gateh": "assets/el-sim/icon-gateh.png?a=f319e736"};
const ICONS = {};
Object.keys(ICONS_SRC).forEach(k=>{const im=new Image();im.onload=()=>draw();im.src=ICONS_SRC[k];ICONS[k]=im;});
// ---- terrain: one mosaic of the game's own render (see generator header) ----
const TERR_SRC = {"world":{"w":2688,"h":3888,"worldPerPx":32,"x0":0,"y0":0,"img":"assets/el-sim/world-mosaic.jpg?a=a9c70139"},"district":{"w":2464,"h":5873,"worldPerPx":8,"x0":0,"y0":750,"img":"assets/el-sim/district-mosaic.jpg?a=93c12ff2"}};
// two sheets of the game's own render: the whole map at 32 world/px and the home
// district at 8. Each maps 1 mosaic px -> worldPerPx/16 display px, so both land on
// the tile lattice exactly; the finer sheet simply draws on top where it applies.
const TERR = {};
['world','district'].forEach(k=>{
  const t = TERR_SRC[k], im = new Image();
  im.onload = ()=>draw(); im.src = t.img;
  TERR[k] = {im, dx: t.x0*TW/2, dy: (t.y0-Y0)*TH/2,
             dw: t.w*t.worldPerPx/16, dh: t.h*t.worldPerPx/16, wpp: t.worldPerPx, w: t.w, h: t.h};
});

// ---- grids ----
const gBlock = new Uint8Array(N);
// whole-map blocked mask, unpacked from the 74 KB bitmask (1 bit per lattice tile,
// row-major over cols = 384 cells; tile x = col*2 + (y&1))
(function(){
  const bin = atob(D.mask.b64), cols = D.mask.cols;
  for(let y=0;y<D.mask.rows;y++){
    const par = y&1;
    for(let c=0;c<cols;c++){
      const i = y*cols+c;
      if(bin.charCodeAt(i>>3) & (1<<(i&7))){ const x=c*2+par; if(inCrop(x,y)) gBlock[idx(x,y)]=1; }
    }
  }
})();
const gLegalV = new Uint8Array(N);
D.legalV.forEach(s=>{const [x,y]=s.split(';').map(Number); if(inCrop(x,y)) gLegalV[idx(x,y)]=1;});
// alliance table: index 1..31 in the claim grid, colour by server (our own three keep
// their familiar green / blue / amber)
const AIDN = {}, CL = {}, TAG = {}, ANAME = {}, ASRV = {};
D.alliances.forEach((a,i)=>{ const n=i+1;
  AIDN[a[0]]=n; CL[n]=a[4]; TAG[a[0]]=a[1]; ANAME[a[0]]=a[2]; ASRV[a[0]]=a[3];
});
const tagOf = (aid)=> TAG[aid] || ('a'+aid);
const aidOfIdx = {}; D.alliances.forEach((a,i)=>aidOfIdx[i+1]=a[0]);

function zoneBoxUV(px,py,isFort){
  const [u0,v0]=uv(px,py);
  return isFort? [u0-4,u0+5,v0-5,v0+4] : [u0-3,u0+3,v0-3,v0+3];
}
function zoneTiles(px,py,isFort){
  const b=zoneBoxUV(px,py,isFort); const t=[];
  for(let u=b[0];u<=b[1];u++) for(let v=b[2];v<=b[3];v++) t.push(xy(u,v));
  return t;
}
function bodyTiles(px,py,isFort){
  return isFort? [[px,py],[px+1,py+1],[px-1,py+1],[px,py+2]] : [[px,py]];
}
// a fixed building's body is a w x w square in uv space with its anchor at the north
// corner, so a 4-wide Eternal City covers 16 tiles, not the 4 a fort does
function bodyTilesW(X,Y,w){
  const [u0,v0]=uv(X,Y), out=[];
  for(let du=0;du<w;du++) for(let dv=0;dv<w;dv++) out.push(xy(u0+du, v0-dv));
  return out;
}
const fixCentre = (f)=> [f.X, f.Y + (f.w||2) - 1];
function fixedBox(X,Y,w,lw){
  const l=X+1-lw, c=Y+w-1;
  const u0=(l+c)/2, v0=(l-c)/2;
  return [u0, u0+lw-1, v0, v0+lw-1];
}

const gClaim = new Uint8Array(N);   // alliance id number
const gExcl  = new Uint8Array(N);
const gBody  = new Uint8Array(N);
const S = D.structs.map((a,i)=>({x:a[0],y:a[1],fort:!!a[2],owner:a[3],st:a[4],st2:a[5],i,
                                 kind:'struct', depth:(a[1]-Y0)*TH/2}));
S.forEach(s=>{
  const an=AIDN[s.owner]; if(!an) return;
  zoneTiles(s.x,s.y,s.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gClaim[idx(x,y)]=an; });
  bodyTiles(s.x,s.y,s.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gBody[idx(x,y)]=1; });
});
// build_type -> sprite (from kvk_building.building_image)
const FIXICON = {3:'outpost',4:'base',5:'ps',6:'mfort',7:'research',8:'city',9:'gate',10:'ark'};
const FIX = D.fixed.map(f=>({X:f[0],Y:f[1],bt:f[2],w:f[3],lw:f[4],sid:f[5],tag:f[6],id:f[7],
                             name:f[8], horiz:!!f[9], kind:'fixed', depth:(f[1]-Y0)*TH/2}));
// gRing: the 1-tile border ring of a Lv.1 Gate WE own is placeable
// (checkPosEnableInKVK) even though the square is claimed. No gate is ours in this
// snapshot, so this is dormant but correct if one is captured.
const gRing = new Uint8Array(N);
FIX.forEach(f=>{
  const b=fixedBox(f.X,f.Y,f.w,f.lw);
  // integer bounds: (l+c) can be odd on some rows, which would put a naive
  // integer walk off-lattice
  const u0=Math.ceil(b[0]), u1=Math.floor(b[1]), v0=Math.ceil(b[2]), v1=Math.floor(b[3]);
  const ownGate = f.bt===9 && f.sid===2864;
  const an = AIDN[Object.keys(TAG).find(a=>TAG[a]===f.tag)] || 0;
  for(let u=u0;u<=u1;u++) for(let v=v0;v<=v1;v++){
    const [x,y]=xy(u,v); if(!inCrop(x,y)) continue;
    const i=idx(x,y);
    const onRing = (u===u0||u===u1||v===v0||v===v1);
    // an owned building carries a territory record, and the fixed-building square
    // is only consulted when a tile has NO record -> don't set gExcl for those
    if(f.sid){ if(!gClaim[i]) gClaim[i]=an; if(ownGate&&onRing) gRing[i]=1; }
    else gExcl[i]=1;
  }
  bodyTilesW(f.X,f.Y,f.w||2).forEach(([x,y])=>{ if(inCrop(x,y)) gBody[idx(x,y)]=1; });
});

// ---- jump overlay: east landing tiles AND the west tiles that reach them ----
const gJump  = new Uint8Array(N);   // east side, past the wall
const gJumpW = new Uint8Array(N);   // west side, a PS here spans the wall
const JUMPS = D.jumps.corridors || [];
JUMPS.forEach(c=>{
  (c.east||[]).forEach(([x,y])=>{ if(inCrop(x,y)) gJump[idx(x,y)]=1; });
  (c.west||[]).forEach(([x,y])=>{ if(inCrop(x,y)) gJumpW[idx(x,y)]=1; });
});

// ---- other warzones' crossings (surveyed, not oracle-verified) ----
const WJ = D.jumpsAll || {gates:[], pockets:[]};
const gAltHome = new Uint8Array(N), gAltTarget = new Uint8Array(N);
const ALT = [];
WJ.gates.forEach(g=>{
  (g.corridors||[]).forEach(c=>{
    if(c.sid === 2864) return;                   // ours is drawn from the detailed pass
    ALT.push({gate:g.gate, name:g.name, sid:c.sid, tags:c.tags, pairs:c.pairs,
              homeTiles:c.homeTiles, targetTiles:c.targetTiles, best:c.best, sample:c.sample});
    (c.sample||[]).forEach(([hx,hy,tx,ty])=>{
      if(inCrop(hx,hy)) gAltHome[idx(hx,hy)]=1;
      if(inCrop(tx,ty)) gAltTarget[idx(tx,ty)]=1;
    });
  });
});
const POCKETS = WJ.pockets || [];
const DEAD = POCKETS.filter(p=>!p.gates);        // no gate on it -> nobody can operate there

// ---- power ----
function boxesTouch(b1,b2){
  const du=Math.max(b1[0]-b2[1],b2[0]-b1[1],0);
  const dv=Math.max(b1[2]-b2[3],b2[2]-b1[3],0);
  return du<=1 && dv<=1 && !(du===1&&dv===1);
}
function powerOf(aid, extra){
  const list=S.filter(s=>s.owner===aid&&s.st===3).map(s=>({box:zoneBoxUV(s.x,s.y,s.fort),fort:s.fort,ref:s}));
  (extra||[]).forEach(p=>list.push({box:zoneBoxUV(p.x,p.y,p.fort),fort:p.fort,ref:p}));
  const n=list.length, adj=Array.from({length:n},()=>[]);
  for(let i=0;i<n;i++)for(let j=i+1;j<n;j++) if(boxesTouch(list[i].box,list[j].box)){adj[i].push(j);adj[j].push(i);}
  const pw=new Set(), st=[];
  list.forEach((m,i)=>{ if(m.fort){pw.add(i);st.push(i);} });
  while(st.length){const k=st.pop(); adj[k].forEach(nb=>{if(!pw.has(nb)){pw.add(nb);st.push(nb);}});}
  const map=new Map(); list.forEach((m,i)=>map.set(m.ref,pw.has(i))); return map;
}
const powerByAid={};
Object.keys(AIDN).forEach(k=>{ powerByAid[k]=powerOf(+k,null); });

// ---- plan ----
let plan=[];
// which alliance a planned structure is for. Dog / MSS / Cat, sticky between placements.
const PLAN_ALLI = ['Dog*','MSS*','Cat+'];
let planAlli = (function(){ try{ const v=localStorage.getItem('elSimAlli'); return PLAN_ALLI.indexOf(v)>=0?v:'Dog*'; }catch(e){ return 'Dog*'; } })();
// Undo on a shared document can't be a snapshot restore — that would stamp on
// whatever a co-planner did meanwhile. Each of my edits records its inverse op and
// undo simply sends that.
function syncUndoBtn(){ const b=document.getElementById('undoBtn'); if(b) b.disabled=!myOps.length; }
function undo(){
  if(!myOps.length) return flash('Nothing of yours left to undo');
  const inv = myOps.pop(); syncUndoBtn();
  if(!inv || !inv.op) return;
  const ops = inv.op==='__batch' ? inv.ops : [inv];
  pushOps(ops).then(ok=>{ if(ok) flash('Undone'); });
}
try{
  const st=JSON.parse(localStorage.getItem('elSimPlan4')||'null');
  const items=st&&Array.isArray(st.items)?st.items:(Array.isArray(st)?st:[]);
  plan=items.filter(p=>p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&(p.x+p.y)%2===0&&typeof p.fort==='boolean');
  plan.forEach(p=>{ if(PLAN_ALLI.indexOf(p.alli)<0) p.alli='Dog*'; });
  if(st&&st.snapshot&&st.snapshot!==D.snapshot) setTimeout(()=>flash('Plan was made on the '+st.snapshot+' snapshot; territory has changed since'),600);
}catch(e){ plan=[]; }
const gPlanClaim=new Uint8Array(N), gPlanBody=new Uint8Array(N);
function rebuildPlanGrids(){
  lodDirty=true;
  gPlanClaim.fill(0); gPlanBody.fill(0);
  plan.forEach(p=>{
    zoneTiles(p.x,p.y,p.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gPlanClaim[idx(x,y)]=1; });
    bodyTiles(p.x,p.y,p.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gPlanBody[idx(x,y)]=1; });
  });
}
function zoneCovers(p,x,y){
  const b=zoneBoxUV(p.x,p.y,p.fort); const [u,v]=uv(x,y);
  return u>=b[0]&&u<=b[1]&&v>=b[2]&&v<=b[3];
}
const BAND=D.legalBand;
function inBand(x,y){ return x>=BAND.x0&&x<=BAND.x1&&y>=BAND.y0&&y<=BAND.y1; }
// ---- fort budget -----------------------------------------------------------
// The cap is per ALLIANCE, so Dog / MSS / Cat each get their own. This used to count
// our own built forts plus EVERY planned fort against one number, so planning an MSS
// fort ate Dog's slot. A fort marked for pickup stops counting as built (that is the
// whole point of picking it up) — matched by tile, so the marker is authoritative.
const OUR_AID = {};
(function(){ const mySid = ASRV[D.myAid];
  Object.keys(TAG).forEach(a=>{ if(ASRV[a]===mySid && PLAN_ALLI.indexOf(TAG[a])>=0) OUR_AID[TAG[a]]=+a; }); })();
function isPickedUp(x,y){ return (SP.pickups||[]).some(p=>p.x===x&&p.y===y); }
function ourForts(alli){ const aid=OUR_AID[alli]; return aid?S.filter(s=>s.fort&&s.owner===aid):[]; }
function fortBudget(alli){
  const own = ourForts(alli);
  const dropped = own.filter(s=>isPickedUp(s.x,s.y)).length;
  const built = own.length - dropped;
  const planned = plan.filter(p=>p.fort && (p.alli||'Dog*')===alli).length;
  const cap = D.live.maxForts;
  return {built, dropped, planned, cap, free: Math.max(0, cap-built-planned)};
}
// mirrors NWorldAddingItem.UpdateGround's order per body tile
function validate(px,py,isFort,alli){
  const forWhom = alli || planAlli;
  if(isFort){
    const b = fortBudget(forWhom);
    if(b.free <= 0) return {ok:false, reason:forWhom+' fort cap reached ('+b.built+' built'
      +(b.planned?' + '+b.planned+' planned':'')+' of '+b.cap
      +(b.dropped?'; '+b.dropped+' already marked for pickup':'')+')'};
  }
  for(const [x,y] of bodyTiles(px,py,isFort)){
    if(!inCrop(x,y)) return {ok:false,reason:'outside the mapped area'};
    const i=idx(x,y);
    if(gBlock[i]) return {ok:false,reason:'mountain / blocked terrain'};
    if(gBody[i]) return {ok:false,reason:'occupied by a structure'};
    if(gPlanBody[i]) return {ok:false,reason:'occupied by a planned structure'};
    if(gPlanClaim[i]) return {ok:false,reason:'inside a planned zone'};
    if(gRing[i]) continue;                       // own-gate ring: placeable
    if(gClaim[i]) return {ok:false,reason:tagOf(aidOfIdx[gClaim[i]])+' claimed tile'};
    if(gExcl[i]) return {ok:false,reason:'fixed-building zone'};
    // inside the wall corridor we probed the live client tile-by-tile, so its verdict
    // also applies: it catches bases/cities this static model cannot see
    if(inBand(x,y) && !gLegalV[i]) return {ok:false,reason:'blocked in game (base, city or unit on the tile)'};
  }
  return {ok:true};
}
let _pp=null;
function invalidatePP(){ _pp=null; }
function planPowered(){
  if(_pp) return _pp;
  const extras=plan.map(p=>({x:p.x,y:p.y,fort:p.fort,__p:p}));
  const m=powerOf(D.myAid,extras);
  _pp=new Map(); extras.forEach(e=>_pp.set(e.__p,m.get(e))); return _pp;
}

// ---- notes + ink rendering / hit-testing -------------------------------------
function tileToScr(tx,ty){ const [wx,wy]=[(tx-X0)*TW/2,(ty-Y0)*TH/2]; return scr(wx,wy); }
function drawInk(){
  const k=zoom*devicePixelRatio;
  (SP.strokes||[]).forEach(st=>{
    if(!st.pts||st.pts.length<2) return;
    ctx.globalAlpha = isErasing(st.id,'s') ? 0.25 : 1;
    ctx.beginPath();
    st.pts.forEach((p,i)=>{ const [sx,sy]=tileToScr(p[0],p[1]); i?ctx.lineTo(sx,sy):ctx.moveTo(sx,sy); });
    ctx.strokeStyle=st.color; ctx.lineWidth=Math.max(1.6, st.width*k*.95);
    ctx.lineJoin='round'; ctx.lineCap='round'; ctx.stroke();
    ctx.globalAlpha = 1;
  });
  if(inkPath.length>1){                       // the stroke being drawn right now
    ctx.beginPath();
    inkPath.forEach((p,i)=>{ const [sx,sy]=tileToScr(p[0],p[1]); i?ctx.lineTo(sx,sy):ctx.moveTo(sx,sy); });
    ctx.strokeStyle=inkColor; ctx.lineWidth=Math.max(1.6, inkWidth*k*.95);
    ctx.lineJoin='round'; ctx.lineCap='round'; ctx.stroke();
  }
}
function drawNotes(){
  const k=zoom*devicePixelRatio;
  (SP.notes||[]).forEach(n=>{
    const [sx,sy]=tileToScr(n.x,n.y);
    if(sx<-80||sy<-40||sx>cv.width+80||sy>cv.height+40) return;
    const r=Math.max(3.5, 5*k*.7);
    ctx.beginPath(); ctx.moveTo(sx,sy); ctx.lineTo(sx-r,sy-r*2.1); ctx.lineTo(sx+r,sy-r*2.1); ctx.closePath();
    ctx.fillStyle=n.color; ctx.fill();
    ctx.strokeStyle='#0d1117'; ctx.lineWidth=1; ctx.stroke();
    if(zoom>0.55){
      const t=n.text.length>34?n.text.slice(0,33)+'…':n.text;
      ctx.font=`${10.5*k*.7}px sans-serif`; ctx.textAlign='left';
      const w=ctx.measureText(t).width+8*k*.7, h=13*k*.7;
      ctx.fillStyle='#0b0f14ee'; ctx.fillRect(sx+r+2, sy-r*2.1-h*0.75, w, h);
      ctx.strokeStyle=n.color+'99'; ctx.lineWidth=1; ctx.strokeRect(sx+r+2, sy-r*2.1-h*0.75, w, h);
      ctx.fillStyle='#f0f6fc'; ctx.fillText(t, sx+r+6, sy-r*2.1+h*0.1);
    }
  });
}
// Hit-testing is done in SCREEN distance, not tile distance: a fixed tile radius is
// a huge target zoomed in and an unhittable one zoomed out. `px` is how close the
// pointer has to be on screen; converted to tile units for the maths.
function tolTiles(px){ return (px||22) / Math.max(0.05, zoom * TW / 2); }
function noteAt(tx,ty,px){
  const tol=tolTiles(px||22), t2=tol*tol;
  let best=null,bd=1e9;
  (SP.notes||[]).forEach(n=>{ const d=(n.x-tx)**2+((n.y-ty)*1.38)**2; if(d<bd&&d<t2){bd=d;best=n;} });
  return best;
}
// distance from a point to a segment, in tile units with y scaled to match x on screen
function segDist2(px_,py_,ax,ay,bx,by){
  const sy=1.38;                                  // TW/TH: makes y comparable to x
  const Ax=ax, Ay=ay*sy, Bx=bx, By=by*sy, Px=px_, Py=py_*sy;
  const dx=Bx-Ax, dy=By-Ay, L2=dx*dx+dy*dy;
  let t = L2 ? ((Px-Ax)*dx + (Py-Ay)*dy) / L2 : 0;
  t = Math.max(0, Math.min(1, t));
  const cx=Ax+t*dx, cy=Ay+t*dy;
  return (Px-cx)**2 + (Py-cy)**2;
}
function strokeAt(tx,ty,px){
  const tol=tolTiles(px||22), t2=tol*tol;
  let best=null,bd=1e9;
  (SP.strokes||[]).forEach(st=>{
    const pts=st.pts||[];
    for(let i=1;i<pts.length;i++){
      const d=segDist2(tx,ty,pts[i-1][0],pts[i-1][1],pts[i][0],pts[i][1]);
      if(d<bd&&d<t2){ bd=d; best=st; }
    }
    if(pts.length===1){ const d=segDist2(tx,ty,pts[0][0],pts[0][1],pts[0][0],pts[0][1]);
      if(d<bd&&d<t2){ bd=d; best=st; } }
  });
  return best;
}
// ---- planned item: hit-test + edit in place ---------------------------------
// A planned structure is editable from the map itself, not just the sidebar row —
// on a phone the sidebar is a sheet, so tapping the thing you just placed has to work.
function planAt(tx,ty){
  const rx=Math.round(tx), ry=Math.round(ty);
  for(const p of plan){
    if(bodyTiles(p.x,p.y,p.fort).some(([bx,by])=>bx===rx&&by===ry)) return p;
  }
  // near miss: pick the closest within ~2 tiles so fat fingers still land
  let best=null,bd=1e9;
  plan.forEach(p=>{ const d=(p.x-tx)**2+((p.y-ty)*0.7)**2; if(d<bd&&d<9){bd=d;best=p;} });
  return best;
}
// ---- eraser: a swipe, not a tap. Dragging never pans while Erase is selected, it
// rubs out whatever it passes over — ink, notes, and planned structures — then sends
// one batch so a sweep is a single shared edit (and a single undo).
const ERASE_PX = 26;
function eraseSweep(pt){
  eraseCursor = pt;
  const [tx,ty] = pt;
  const st = strokeAt(tx,ty,ERASE_PX);
  if(st && !eraseHits['s'+st.id]) eraseHits['s'+st.id] = {op:{op:'strokeDel', id:st.id},
    undo:{op:'stroke', pts:st.pts, color:st.color, width:st.width}};
  const n = noteAt(tx,ty,ERASE_PX);
  if(n && !eraseHits['n'+n.id]) eraseHits['n'+n.id] = {op:{op:'noteDel', id:n.id},
    undo:{op:'note', x:n.x, y:n.y, text:n.text, color:n.color}};
  const it = planAt(tx,ty);
  if(it && !eraseHits['i'+it.id]) eraseHits['i'+it.id] = {op:{op:'del', id:it.id},
    undo:{op:'add', kind:it.fort?'fort':'ps', x:it.x, y:it.y, alli:it.alli}};
}
function eraseCommit(){
  const hits = Object.values(eraseHits);
  eraseHits = {}; eraseCursor = null;
  if(!hits.length){ draw(); return flash('Nothing under the eraser — sweep across it'); }
  const ops = hits.map(h=>h.op), undos = hits.map(h=>h.undo);
  // one shared edit for the whole sweep; undo puts all of it back
  pushOps(ops, ()=>({op:'__batch', ops:undos}));
  draw();
}
function isErasing(id, kind){ return !!eraseHits[kind+id]; }
let itemEditor=null;
function closeItemEditor(){ if(itemEditor){ itemEditor.remove(); itemEditor=null; } }
function openItemEditor(p){
  closeItemEditor();
  const box=document.createElement('div');
  box.id='itemEdit';
  box.style.cssText='position:fixed;left:50%;bottom:16px;transform:translateX(-50%);z-index:30;'
    +'background:var(--card);border:1px solid var(--border);border-radius:10px;padding:10px 12px;'
    +'box-shadow:0 8px 24px #000a;font-size:12px;max-width:94vw;';
  const col=(a)=> a==='MSS*'?'#388bfd':(a==='Cat+'?'#d29922':'#3fb950');
  box.innerHTML='<div style="margin-bottom:7px">'
    +'<b>'+(p.fort?'Planned Fort':'Planned Power Station')+'</b> '+p.x+';'+p.y
    +(p.by?' <span style="color:var(--muted)">by '+esc(p.by)+'</span>':'')+'</div>'
    +'<div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center">'
    + PLAN_ALLI.map(a=>'<button type="button" class="tbtn ie-a" data-a="'+a+'" style="border-color:'+col(a)
        +';color:'+col(a)+(a===(p.alli||'Dog*')?';background:'+col(a)+'22':'')+'">'+a+'</button>').join('')
    +'<span style="width:8px"></span>'
    +'<button type="button" class="tbtn danger ie-del">Delete</button>'
    +'<button type="button" class="tbtn ie-close">Close</button></div>';
  document.body.appendChild(box);
  itemEditor=box;
  box.querySelectorAll('.ie-a').forEach(b=>b.onclick=()=>{
    const to=b.dataset.a, from=p.alli;
    closeItemEditor();
    if(to===from) return;
    pushOps([{op:'setAlli', id:p.id, alli:to}], ()=>({op:'setAlli', id:p.id, alli:from}));
  });
  box.querySelector('.ie-del').onclick=()=>{
    closeItemEditor();
    pushOps([{op:'del', id:p.id}], ()=>({op:'add', kind:p.fort?'fort':'ps', x:p.x, y:p.y, alli:p.alli}));
  };
  box.querySelector('.ie-close').onclick=closeItemEditor;
}
// ---- existing fort: mark it as one we intend to pick up ----------------------
// Picking a fort up before the battle frees its slot against that alliance's cap, so
// the slot can be planned somewhere useful. This does NOT vacate its ground here: the
// map still shows the fort and its zone from the live snapshot, and the power network
// is still computed with it, because we only know it is *intended* to come down.
function ourFortAt(tx,ty){
  const rx=Math.round(tx), ry=Math.round(ty);
  const own=S.filter(s=>s.fort && OUR_AID[tagOf(s.owner)]);
  for(const s of own) if(bodyTiles(s.x,s.y,true).some(([bx,by])=>bx===rx&&by===ry)) return s;
  let best=null,bd=1e9;                                    // near miss: fat fingers
  own.forEach(s=>{ const d=(s.x-tx)**2+((s.y+1-ty)*0.7)**2; if(d<bd&&d<12){bd=d;best=s;} });
  return best;
}
function openFortEditor(s){
  closeItemEditor();
  const tag=tagOf(s.owner), pu=(SP.pickups||[]).find(p=>p.x===s.x&&p.y===s.y), b=fortBudget(tag);
  const box=document.createElement('div');
  box.id='itemEdit';
  box.style.cssText='position:fixed;left:50%;bottom:16px;transform:translateX(-50%);z-index:30;'
    +'background:var(--card);border:1px solid var(--border);border-radius:10px;padding:10px 12px;'
    +'box-shadow:0 8px 24px #000a;font-size:12px;max-width:94vw;';
  box.innerHTML='<div style="margin-bottom:5px"><b style="color:'+alliCol(tag)+'">'+esc(tag)+' Fort</b> '
    + s.x+';'+s.y+' <span style="color:var(--muted)">already built</span></div>'
    +'<div class="note" style="margin:0 0 8px">'+esc(tag)+': '+b.built+' built'
    + (b.planned?' + '+b.planned+' planned':'') + ' of '+b.cap+' &middot; <b style="color:'
    + (b.free?'var(--green)':'var(--red)')+'">'+b.free+' free</b>'
    + (pu?'<br>Marked for pickup by '+esc(pu.by||'?'):'')+'</div>'
    +'<div style="display:flex;gap:6px;flex-wrap:wrap;align-items:center">'
    + (pu ? '<button type="button" class="tbtn fe-keep">Keep this one after all</button>'
          : '<button type="button" class="tbtn fe-pick" style="border-color:var(--jump);color:var(--jump)">'
            +'We pick this one up</button>')
    +'<button type="button" class="tbtn ie-close">Close</button></div>';
  document.body.appendChild(box);
  itemEditor=box;
  const pick=box.querySelector('.fe-pick');
  if(pick) pick.onclick=()=>{ closeItemEditor();
    pushOps([{op:'pickup', x:s.x, y:s.y, alli:tag}],
            (applied)=>({op:'pickupDel', id:(applied[0]||{}).id})); };
  const keep=box.querySelector('.fe-keep');
  if(keep) keep.onclick=()=>{ closeItemEditor();
    pushOps([{op:'pickupDel', id:pu.id}], ()=>({op:'pickup', x:s.x, y:s.y, alli:pu.alli})); };
  box.querySelector('.ie-close').onclick=closeItemEditor;
}
// ---- note editor (small prompt-based flow; works the same on phone) ----
function addNoteAt(tx,ty){
  const text=(window.prompt('Note for this spot (everyone sees it):')||'').trim();
  if(!text) return;
  pushOps([{op:'note', x:+tx.toFixed(1), y:+ty.toFixed(1), text, color:inkColor}],
          (applied)=>({op:'noteDel', id:(applied[0]||{}).id}));
}
function openNote(n){
  const t=(window.prompt('Edit the note (empty deletes it):', n.text)||'').trim();
  if(t===n.text) return;
  if(!t){ pushOps([{op:'noteDel', id:n.id}], ()=>({op:'note', x:n.x, y:n.y, text:n.text, color:n.color})); return; }
  pushOps([{op:'note', id:n.id, x:n.x, y:n.y, text:t, color:n.color}],
          ()=>({op:'note', id:n.id, x:n.x, y:n.y, text:n.text, color:n.color}));
}
// ---- fort budget panel: each alliance's own cap, and what a pickup frees ----
function alliCol(a){ return a==='MSS*'?'#388bfd':(a==='Cat+'?'#d29922':'#3fb950'); }
function renderForts(){
  const sf=document.getElementById('sFort');
  if(sf){ const b=fortBudget('Dog*'); sf.textContent=(b.built+b.planned)+' / '+b.cap; }
  const el=document.getElementById('fortBudget'); if(!el) return;
  const rows = PLAN_ALLI.map(a=>{
    const b=fortBudget(a);
    const bits=[b.built+' built'];
    if(b.planned) bits.push(b.planned+' planned');
    if(b.dropped) bits.push('<span style="color:var(--jump)">'+b.dropped+' picking up</span>');
    return '<div class="lrow" style="justify-content:space-between;gap:10px">'
      +'<span><span class="sw" style="background:'+alliCol(a)+'"></span>'+a+'</span>'
      +'<span>'+bits.join(' &middot; ')+' &rarr; <b style="color:'
      + (b.free?'var(--green)':'var(--red)')+'">'+b.free+' free</b></span></div>';
  }).join('');
  const pus=(SP.pickups||[]).slice().sort((a,b)=>a.y-b.y);
  const list = pus.length
    ? '<div class="note">Being picked up: '+pus.map(p=>'<b class="pu-go" data-x="'+p.x+'" data-y="'+p.y
        +'" style="color:var(--jump);cursor:pointer">'+esc(p.alli)+' '+p.x+';'+p.y+'</b>').join(', ')
        +'. Tap a fort on the map to change it.</div>'
    : '<div class="note">The cap is per alliance. Tap one of our forts on the map to mark it as one we will '
      +'pick up &mdash; that frees its slot to plan somewhere else.</div>';
  el.innerHTML = rows + list;
  el.querySelectorAll('.pu-go').forEach(b=>b.onclick=()=>flyTo(+b.dataset.x,+b.dataset.y,2.2));
}
function renderNotes(){
  const el=document.getElementById('noteList'); if(!el) return;
  el.innerHTML='';
  if(!(SP.notes||[]).length){ el.innerHTML='<div class="note">No notes yet. Pick <b>Note</b> and tap the map.</div>'; return; }
  SP.notes.slice().sort((a,b)=>b.at-a.at).forEach(n=>{
    const d=document.createElement('div'); d.className='noterow'; d.style.borderLeftColor=n.color;
    d.innerHTML='<span>'+esc(n.text.slice(0,80))+'<br><span style="color:var(--muted);font-size:10px">'
      +Math.round(n.x)+';'+Math.round(n.y)+' &middot; '+esc(n.by||'?')+'</span></span>'
      +'<span class="del" title="Delete">&times;</span>';
    d.onclick=()=>flyTo(Math.round(n.x),Math.round(n.y),2.2);
    d.querySelector('.del').onclick=(ev)=>{ ev.stopPropagation();
      pushOps([{op:'noteDel', id:n.id}], ()=>({op:'note', x:n.x, y:n.y, text:n.text, color:n.color})); };
    el.appendChild(d);
  });
}
function renderClog(){
  const el=document.getElementById('clog'); if(!el) return;
  el.innerHTML='';
  const log=SP.changelog||[];
  if(!log.length){ el.innerHTML='<div class="note">No edits recorded yet.</div>'; return; }
  log.slice(0,40).forEach(e=>{
    const d=document.createElement('div'); d.className='clogrow';
    const t=e.at?new Date(e.at).toLocaleString([], {month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'';
    d.innerHTML='<b>'+esc(e.by||'?')+'</b> '+esc(e.what)+'<br><span style="opacity:.7">'+t+'</span>';
    el.appendChild(d);
  });
}

// ---- shared plan: the worker owns the document, we send ops -------------------
// Several people plan at once, so nothing here PUTs a whole plan. Notes and ink are
// kept in TILE space so they stay put at any zoom.
const API = 'https://push-worker.27tb8s6fct.workers.dev';
const INK = ['#f85149','#d29922','#3fb950','#39c5cf','#79c0ff','#a371f7','#ffffff','#0d1117'];
let SP = {rev:-1, items:[], pickups:[], notes:[], strokes:[], changelog:[], counts:{}};
let inkPath = [];
let inkColor = (function(){ try{ const c=localStorage.getItem('elSimInk'); return INK.indexOf(c)>=0?c:INK[0]; }catch(e){ return INK[0]; } })();
let inkWidth = 3, shareOK = false, myOps = [];   // myOps = local undo stack of {undo:op}

function whoAmI(){
  try { const v=localStorage.getItem('playerIdentity'); if(!v||v==='anonymous') return '';
        const j=JSON.parse(v); return (j&&j.name)||''; } catch(e){ return ''; }
}
function pw(){ try { return localStorage.getItem('elSimPw')||''; } catch(e){ return ''; } }

function setShareState(msg, bad){
  const el=document.getElementById('shareState');
  if(el) el.innerHTML = bad ? '<span style="color:var(--red)">'+msg+'</span>' : msg;
}
function adoptPlan(view){
  SP = view;
  if(!Array.isArray(SP.pickups)) SP.pickups = [];      // documents stored before pickups existed
  // the rest of the app still thinks in {x,y,fort} — keep that shape, carry the id
  plan = (view.items||[]).map(i=>({id:i.id, x:i.x, y:i.y, fort:i.kind==='fort', alli:i.alli, by:i.by, at:i.at}));
  shareOK = true;
  rebuildPlanGrids(); invalidatePP(); renderPlan(); renderNotes(); renderClog(); renderForts(); draw();
  const when = view.updatedAt ? new Date(view.updatedAt).toLocaleTimeString() : '';
  setShareState(`Shared with the alliance &middot; rev ${view.rev} &middot; ${view.counts.items} structures, `
    + `${view.counts.notes} notes, ${view.counts.strokes} drawings`
    + (view.updatedBy ? `<br>last edit by <b>${esc(view.updatedBy)}</b> at ${when}` : ''));
}
function esc(t){ return String(t==null?'':t).replace(/[<>&"]/g, c=>({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;'}[c])); }

function pullPlan(){
  return fetch(API+'/elsim/plan', {headers:{'X-El-Sim-Password':pw()}})
    .then(r=>{ if(!r.ok) throw new Error('http '+r.status); return r.json(); })
    .then(adoptPlan)
    .catch(e=>{ shareOK=false; setShareState('Could not reach the shared plan ('+e.message+'). '
      +'You can still look around; edits are paused.', true); });
}
function pushOps(ops, undoOps){
  if(!shareOK){ flash('Shared plan is offline — edit not saved'); return Promise.resolve(false); }
  const me = whoAmI();
  if(!me){ flash('Pick your name first so edits are attributed'); openWhoFromApp(); return Promise.resolve(false); }
  return fetch(API+'/elsim/plan', {method:'POST', headers:{
      'Content-Type':'application/json','X-El-Sim-Password':pw(),'X-Player-Name':me
    }, body: JSON.stringify({ops})})
    .then(r=>r.json())
    .then(j=>{
      if(!j || !j.ok){ flash('Edit refused: '+((j&&j.error)||'unknown')); return false; }
      (j.rejected||[]).forEach(r=>flash('Refused ('+r.op+'): '+r.reason));
      if(j.plan) adoptPlan(j.plan);
      if(undoOps && (j.applied||[]).length){
        // remember how to reverse it, filling in ids the server just assigned
        myOps.push(undoOps(j.applied));
        if(myOps.length>40) myOps.shift();
        syncUndoBtn();
      }
      return true;
    })
    .catch(e=>{ flash('Edit failed: '+e.message); return false; });
}
function openWhoFromApp(){
  const w=document.getElementById('who'); if(w) w.classList.remove('hide');
  const btn=document.getElementById('idchip'); if(btn) btn.click();
}

// ---- canvas ----
const cv=document.getElementById('cv'), ctx=cv.getContext('2d');
let zoom=1, ox=0, oy=0;
function resize(){ cv.width=cv.clientWidth*devicePixelRatio; cv.height=cv.clientHeight*devicePixelRatio; draw(); }
window.addEventListener('resize',resize);
const px=(x,y)=>[(x-X0)*TW/2,(y-Y0)*TH/2];
const scr=(wx,wy)=>[(wx-ox)*zoom*devicePixelRatio,(wy-oy)*zoom*devicePixelRatio];
let showClaims=true, showZones=true, showGrid=false, showMtn=true, showJump=true, showLegal=false, showBlock=false, showAreas=true, showAlt=false;
// ---- low-zoom sheet: one pixel per tile (cell x, tile y), blitted onto the map rect
const LOD_Z=0.42, LODW=D.mask.cols, LODH=D.mask.rows;
const lod=document.createElement('canvas'); lod.width=LODW; lod.height=LODH;
let lodDirty=true;
const hex2rgb=(h)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
const CLRGB={}; Object.keys(CL).forEach(k=>CLRGB[k]=hex2rgb(CL[k]));
function buildLOD(){
  const g=lod.getContext('2d'), im=g.createImageData(LODW,LODH), d=im.data;
  for(let y=0;y<LODH;y++){
    const par=y&1;
    for(let c=0;c<LODW;c++){
      const x=c*2+par; if(!inCrop(x,y)) continue;
      const i=idx(x,y), o=(y*LODW+c)*4;
      if(gBlock[i]){ d[o]=38;d[o+1]=44;d[o+2]=54;d[o+3]=showMtn?(showBlock?190:0):235; continue; }
      if(showClaims&&gPlanClaim[i]){ d[o]=121;d[o+1]=192;d[o+2]=255;d[o+3]=190; continue; }
      if(showClaims&&gClaim[i]){ const c3=CLRGB[gClaim[i]]||[139,148,158];
        d[o]=c3[0];d[o+1]=c3[1];d[o+2]=c3[2];d[o+3]=170; continue; }
      if(showZones&&gExcl[i]){ d[o]=248;d[o+1]=81;d[o+2]=73;d[o+3]=60; }
    }
  }
  g.putImageData(im,0,0); lodDirty=false;
}
// ---- area (district) boundaries: segments in [cellX,row] units, row = tile y / 2
const ASEG=D.areas.segs, ALAB=D.areas.labels;
const AX=(c)=>c*TW, AY=(r)=>r*TH;              // 2 x-units = TW px, 2 rows = TH px
const AREA_NAME=(a,dom)=>{
  if(a===31) return 'Eternal City';
  if(a>=100) return '';
  if(a>=21) return 'Inner ring';
  if(a>=11) return 'Mid ring';
  return dom?('S'+dom):('sector '+a);
};
let tool='pan', hover=null;

function tilePath(x,y,scale){
  const [wx,wy]=px(x,y); const [sx,sy]=scr(wx,wy);
  const hw=TW/2*zoom*devicePixelRatio*(scale||1), hh=TH/2*zoom*devicePixelRatio*(scale||1);
  ctx.moveTo(sx,sy-hh); ctx.lineTo(sx+hw,sy); ctx.lineTo(sx,sy+hh); ctx.lineTo(sx-hw,sy); ctx.closePath();
}
function visRange(){
  const cssW=cv.clientWidth, cssH=cv.clientHeight;
  return [Math.max(X0,Math.floor(ox/(TW/2))+X0-2), Math.min(X1,Math.ceil((ox+cssW/zoom)/(TW/2))+X0+2),
          Math.max(Y0,Math.floor(oy/(TH/2))+Y0-2), Math.min(Y1,Math.ceil((oy+cssH/zoom)/(TH/2))+Y0+2)];
}
const ICON_SPEC = {ps:{w:1.7,cy:0,drop:.55}, fort:{w:2.6,cy:1,drop:1}, outpost:{w:2.3,cy:1,drop:1},
                   gateh:{w:4.2,cy:0,drop:1.15},   // positive_level: east-west wall segment

                   base:{w:2.6,cy:1,drop:1}, gate:{w:2.0,cy:1,drop:1.55}, mfort:{w:2.6,cy:1,drop:1},
                   research:{w:2.6,cy:1,drop:1}, city:{w:3.4,cy:2,drop:1.2}, ark:{w:3.0,cy:4,drop:1.4}};
// All on-map text goes through this. The terrain is pale green with white mountains,
// so bright text alone disappears — every label gets a dark halo behind it.
function mapLabel(text, sx, sy, color, sizePx, align, weight){
  ctx.font = (weight||'600')+' '+sizePx+'px sans-serif';
  ctx.textAlign = align || 'center';
  ctx.lineJoin = 'round';
  ctx.lineWidth = Math.max(2.5, sizePx*0.42);
  ctx.strokeStyle = '#0b0f14e6';
  ctx.strokeText(text, sx, sy);
  ctx.fillStyle = color;
  ctx.fillText(text, sx, sy);
}
function iconH(kind){
  const im=ICONS[kind], spec=ICON_SPEC[kind];
  if(!im||!im.complete||!im.naturalWidth) return TH*zoom*devicePixelRatio;
  return spec.w*TW*zoom*devicePixelRatio*im.naturalHeight/im.naturalWidth;
}
function drawIcon(kind,gx,gy,opts){
  opts=opts||{};
  const im=ICONS[kind], spec=ICON_SPEC[kind];
  if(!spec) return false;              // unknown kind: skip it, never throw mid-pass
  const w=(opts.w||spec.w)*TW*zoom*devicePixelRatio;
  if(!im||!im.complete||!im.naturalWidth||w<13) return false;
  const h=w*im.naturalHeight/im.naturalWidth;
  // opts.exact means gy is already the body centre (fixed buildings compute it from
  // their own width), so don't add the per-kind nudge on top
  const [wx,wy]=px(gx, opts.exact ? gy : gy+spec.cy); const [sx,sy]=scr(wx,wy);
  ctx.save();
  if(opts.gray) ctx.filter='grayscale(70%)';
  ctx.globalAlpha=opts.alpha!==undefined?opts.alpha:1;
  ctx.drawImage(im,sx-w/2,sy+TH*zoom*devicePixelRatio*spec.drop-h,w,h);
  ctx.restore();
  return true;
}
let _raf=0;
function draw(){ if(_raf) return; _raf=requestAnimationFrame(()=>{_raf=0;render();}); }
function render(){
  ctx.clearRect(0,0,cv.width,cv.height);
  const [x0,x1,y0,y1]=visRange();
  // ---- terrain: the game's own render, placed 1:1 on the crop rect ----
  const kx=zoom*devicePixelRatio;
  if(showMtn){
    ctx.imageSmoothingEnabled=true; ctx.imageSmoothingQuality='high';
    // the district sheet is a different capture pass, so its tone differs slightly from
    // the world sheet; only bring it in once it is actually adding detail, otherwise it
    // reads as a bright rectangle over the overview
    ['world','district'].forEach(k=>{
      const t=TERR[k];
      if(!t.im.complete||!t.im.naturalWidth) return;
      if(k==='district'&&zoom<0.34) return;
      const [tx,ty]=scr(t.dx,t.dy);
      ctx.drawImage(t.im,tx,ty,t.dw*kx,t.dh*kx);
    });
  }
  // ---- claims + blocked ----
  // Per-tile diamonds are ~590k paths at whole-map zoom, so below LOD_Z we blit one
  // pre-rendered cell sheet (384x1536, one pixel per tile) scaled onto the same rect.
  if(zoom < LOD_Z){
    if(lodDirty) buildLOD();
    const [tx,ty]=scr(0,0);
    ctx.imageSmoothingEnabled=false;
    ctx.globalAlpha=showMtn?0.66:1;
    ctx.drawImage(lod,tx,ty,(X1-X0+1)*TW/2*kx,(Y1-Y0+1)*TH/2*kx);
    ctx.globalAlpha=1; ctx.imageSmoothingEnabled=true;
  } else
  for(let y=y0;y<=y1;y++){
    for(let x=x0+((x0+y)%2!==0?1:0); x<=x1; x+=2){
      const i=idx(x,y);
      // with the terrain art on the blocked mask is an optional overlay on top of the
      // real mountain; with the art off the mask *is* the terrain
      if(gBlock[i]){
        if(!showMtn){ ctx.fillStyle='#262c36'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
        else if(showBlock){ ctx.fillStyle='#0d1117aa'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
        continue;
      }
      if(showClaims&&gClaim[i]){ ctx.fillStyle=CL[gClaim[i]]+(showMtn?'55':'3d'); ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showClaims&&gPlanClaim[i]){ ctx.fillStyle='#79c0ff3d'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showZones&&gExcl[i]){ ctx.fillStyle='#f8514922'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showLegal&&gLegalV[i]&&!gClaim[i]){ ctx.fillStyle='#3fb95015'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showAlt&&gAltTarget[i]){ ctx.fillStyle='#f0883e55'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showAlt&&gAltHome[i]){ ctx.fillStyle='#39c5cf55'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showJump&&gJumpW[i]){ ctx.fillStyle='#79c0ff66'; ctx.beginPath(); tilePath(x,y,1); ctx.fill();
        ctx.strokeStyle='#79c0ff'; ctx.lineWidth=Math.max(1,.9*kx*.5); ctx.stroke(); }
      if(showJump&&gJump[i]){ ctx.fillStyle='#d2a8ff66'; ctx.beginPath(); tilePath(x,y,1); ctx.fill();
        ctx.strokeStyle='#d2a8ff'; ctx.lineWidth=Math.max(1,.9*kx*.5); ctx.stroke(); }
    }
  }
  if(showGrid&&zoom>1.4){
    ctx.strokeStyle='#ffffff10'; ctx.lineWidth=1; ctx.beginPath();
    for(let y=y0;y<=y1;y++) for(let x=x0+((x0+y)%2!==0?1:0); x<=x1; x+=2) tilePath(x,y,1);
    ctx.stroke();
  }
  // ---- area (district) boundaries straight from the client's own area map ----
  if(showAreas){
    ctx.strokeStyle='#e6edf344'; ctx.lineWidth=Math.max(1,1.1*kx*.5);
    ctx.beginPath();
    ASEG.forEach(([c0,r0,c1,r1])=>{
      const a=scr(AX(c0),AY(r0)), b=scr(AX(c1),AY(r1));
      if((a[0]<0&&b[0]<0)||(a[0]>cv.width&&b[0]>cv.width)||(a[1]<0&&b[1]<0)||(a[1]>cv.height&&b[1]>cv.height)) return;
      ctx.moveTo(a[0],a[1]); ctx.lineTo(b[0],b[1]);
    });
    ctx.stroke();
  }
  // at whole-map zoom the icons are too small to draw, so mark the forts
  if(zoom<LOD_Z){
    S.forEach(s=>{
      if(!s.fort) return;
      const [wx,wy]=px(s.x,s.y); const [sx,sy]=scr(wx,wy);
      if(sx<-8||sy<-8||sx>cv.width+8||sy>cv.height+8) return;
      ctx.beginPath(); ctx.arc(sx,sy,Math.max(2.2,3.4*kx),0,Math.PI*2);
      ctx.fillStyle=CL[AIDN[s.owner]]||'#8b949e'; ctx.fill();
      ctx.strokeStyle=isPickedUp(s.x,s.y)?'#d2a8ff':'#0d1117';   // purple = coming down
      ctx.lineWidth=isPickedUp(s.x,s.y)?2:1; ctx.stroke();
    });
  }
  // ---- zone outlines for our own structures ----
  if(showClaims){
    S.forEach(s=>{
      if(s.owner!==D.myAid) return;
      if(s.x<x0-14||s.x>x1+14||s.y<y0-14||s.y>y1+14) return;
      const powered=powerByAid[s.owner]?powerByAid[s.owner].get(s):true;
      ctx.strokeStyle=CL[1]+(powered?'88':'44');
      ctx.lineWidth=1.2*zoom*devicePixelRatio*.5;
      strokeZone(s.x,s.y,s.fort);
    });
  }
  // ---- structures / fixed buildings / plan, depth-sorted north->south like the
  // game's units layer (terrain is the mosaic underneath, so nothing can paint over
  // a Gate any more) ----
  const kk=zoom*devicePixelRatio;
  const objItems=[];
  S.forEach(s=>{ if(s.x>=x0-14&&s.x<=x1+14&&s.y>=y0-14&&s.y<=y1+14) objItems.push(s); });
  FIX.forEach(f=>{ if(f.X>=x0-16&&f.X<=x1+16&&f.Y>=y0-16&&f.Y<=y1+16) objItems.push(f); });
  const pp=planPowered();
  plan.forEach((p,i)=>objItems.push({kind:'plan',p,i,depth:(p.y-Y0)*TH/2}));
  objItems.sort((a,b)=>a.depth-b.depth);
  const k=kk;
  objItems.forEach(it=>{
    if(it.kind==='struct'){
      const s=it, an=AIDN[s.owner], col=CL[an]||'#8b949e';
      const powered=powerByAid[s.owner]?powerByAid[s.owner].get(s):true;
      const building=s.st===2;
      ctx.beginPath(); bodyTiles(s.x,s.y,s.fort).forEach(([bx,by])=>tilePath(bx,by,0.92));
      ctx.fillStyle=col+(building?'44':'77'); ctx.fill();
      if(!powered&&!building){ ctx.strokeStyle='#f85149'; ctx.lineWidth=1.5*k*.5; ctx.stroke(); }
      // a fort we intend to pick up: dashed purple body so it reads as "not staying"
      const goingAway = s.fort && isPickedUp(s.x,s.y);
      if(goingAway){
        ctx.save(); ctx.setLineDash([5*k*.5,4*k*.5]);
        ctx.strokeStyle='#d2a8ff'; ctx.lineWidth=2*k*.5; ctx.stroke(); ctx.restore();
      }
      drawIcon(s.fort?'fort':'ps', s.x, s.y,
               {alpha: goingAway?.4:(building?.55:(powered?1:.5)), gray: building||goingAway});
      if(s.fort&&zoom>.8){
        const [wx,wy]=px(s.x,s.y+2); const [sx,sy]=scr(wx,wy);
        mapLabel('FORT '+tagOf(s.owner)+(building?' (building)':''), sx, sy+TH*k*.9, '#ffffff', 9.5*k*.7);
        if(goingAway) mapLabel('picking up', sx, sy+TH*k*.9+11*k*.7, '#d2a8ff', 9*k*.7);
      }
    } else if(it.kind==='fixed'){
      const f=it, ctr=fixCentre(f);
      ctx.beginPath(); bodyTilesW(f.X,f.Y,f.w||2).forEach(([bx,by])=>tilePath(bx,by,0.92));
      ctx.fillStyle=f.sid?'#3fb95055':'#6e768155'; ctx.fill();
      ctx.strokeStyle=f.sid?'#3fb950aa':'#f8514966'; ctx.lineWidth=1; ctx.stroke();
      // gates use the sprite that matches their wall: wide for east-west, tall for north-south
      const kindIcon = f.bt===9 ? (f.horiz?'gateh':'gate') : (FIXICON[f.bt]||'outpost');
      drawIcon(kindIcon, ctr[0], ctr[1], {exact:true, w: f.bt===9&&f.horiz ? 4.2 : undefined});
      if(zoom>.9){
        const [wx,wy]=px(ctr[0],ctr[1]+1); const [sx,sy]=scr(wx,wy);
        mapLabel(f.name+' '+f.X+';'+f.Y+(f.tag?' ['+f.tag+']':''), sx, sy+TH*k*1.3,
                 f.sid?'#7ee787':'#e6edf3', 9*k*.7);
      }
    } else if(it.kind==='plan'){
      const p=it.p;
      ctx.beginPath(); bodyTiles(p.x,p.y,p.fort).forEach(([bx,by])=>tilePath(bx,by,0.95));
      const aCol = p.alli==='MSS*'?'#388bfd':(p.alli==='Cat+'?'#d29922':'#3fb950');
      const stCol=pp.get(p)?aCol:'#d29922';
      ctx.fillStyle=aCol+'44'; ctx.fill();
      ctx.strokeStyle=stCol; ctx.lineWidth=2*k*.5; ctx.stroke();
      ctx.strokeStyle=aCol+'88'; ctx.lineWidth=1.2*k*.5; strokeZone(p.x,p.y,p.fort);
      drawIcon(p.fort?'fort':'ps', p.x, p.y, {alpha:.92});
      if(zoom>.9){
        const [wx,wy]=px(p.x,p.y); const [sx,sy]=scr(wx,wy);
        mapLabel('#'+(it.i+1)+' '+(p.alli||'Dog*'), sx, sy-iconH(p.fort?'fort':'ps'), stCol, 10*k*.7, 'center', 'bold');
      }
    }
  });
  // ---- jump callouts: west spot -> east landing, on top of everything ----
  if(showJump){
    const S2=(gx,gy)=>{ const [wx,wy]=px(gx,gy); return scr(wx,wy); };
    // every pair, faint, so the whole corridor reads at a glance
    ctx.save(); ctx.setLineDash([4*k*.5,4*k*.5]); ctx.lineWidth=1.1*k*.5; ctx.strokeStyle='#79c0ff55';
    JUMPS.forEach(c=>(c.pairs||[]).forEach(([wx2,wy2,ex,ey])=>{
      if(ey<y0-24||ey>y1+24) return;
      const a=S2(wx2,wy2), b=S2(ex,ey);
      ctx.beginPath(); ctx.moveTo(a[0],a[1]); ctx.lineTo(b[0],b[1]); ctx.stroke();
    }));
    ctx.restore();
    if(showAlt){
      ctx.save(); ctx.setLineDash([5*k*.5,4*k*.5]); ctx.lineWidth=1.4*k*.5; ctx.strokeStyle='#f0883eaa';
      ALT.forEach(a=>{
        const h=a.best.home, t=a.best.target;
        if(t[1]<y0-40||t[1]>y1+40) return;
        const A=S2(h[0],h[1]), B=S2(t[0],t[1]);
        ctx.beginPath(); ctx.moveTo(A[0],A[1]); ctx.lineTo(B[0],B[1]); ctx.stroke();
        if(zoom>0.5){
          mapLabel('S'+a.sid, (A[0]+B[0])/2, (A[1]+B[1])/2-4*k*.7, '#ffb77c', 9.5*k*.7);
        }
      });
      ctx.restore();
    }
    JUMPS.forEach((c,ci)=>{
      const [bx,by]=c.best;
      if(bx<x0-24||bx>x1+24||by<y0-24||by>y1+24) return;
      const [sx,sy]=S2(bx,by);
      if(c.bestWest){
        const [asx,asy]=S2(c.bestWest[0],c.bestWest[1]);
        ctx.save();
        if(c.westKind==='new') ctx.setLineDash([6*k*.5,4*k*.5]);
        ctx.strokeStyle=c.westKind==='new'?'#79c0ffee':'#d2a8ffcc'; ctx.lineWidth=2*k*.5;
        ctx.beginPath(); ctx.moveTo(asx,asy); ctx.lineTo(sx,sy); ctx.stroke(); ctx.restore();
        // west marker
        ctx.beginPath(); ctx.arc(asx,asy,5*k*.6,0,Math.PI*2);
        ctx.fillStyle=c.westKind==='new'?'#79c0ff':'#3fb950'; ctx.fill();
        ctx.strokeStyle='#0d1117'; ctx.lineWidth=1.2*k*.4; ctx.stroke();
        if(zoom>.7){
          mapLabel((c.westKind==='new'?'NEW PS ':'PS ')+c.bestWest[0]+';'+c.bestWest[1], asx, asy-8*k*.7,
                   c.westKind==='new'?'#a5d6ff':'#7ee787', 9.5*k*.7, 'center', 'bold');
        }
      }
      // east marker
      ctx.beginPath(); ctx.arc(sx,sy,5.8*k*.6,0,Math.PI*2);
      ctx.fillStyle='#d2a8ff'; ctx.fill();
      ctx.strokeStyle='#0b0f14'; ctx.lineWidth=1.6*k*.5; ctx.stroke();
      ctx.fillStyle='#0d1117'; ctx.font=`bold ${8*k*.6}px sans-serif`; ctx.textAlign='center'; ctx.textBaseline='middle';
      ctx.fillText(String(ci+1), sx, sy);
      ctx.textBaseline='alphabetic';
      if(zoom>.7){
        mapLabel('LAND '+bx+';'+by, sx, sy-9*k*.7, '#e2c5ff', 10*k*.7, 'center', 'bold');
      }
    });
  }
  drawInk();
  drawNotes();
  if(tool==='erase'&&eraseCursor){
    const [ex,ey]=tileToScr(eraseCursor[0],eraseCursor[1]);
    ctx.beginPath(); ctx.arc(ex,ey,ERASE_PX*devicePixelRatio,0,Math.PI*2);
    ctx.strokeStyle='#f85149cc'; ctx.lineWidth=2*devicePixelRatio; ctx.setLineDash([5,4]);
    ctx.stroke(); ctx.setLineDash([]);
  }
  // ---- area labels, always legible, on top ----
  if(showAreas){
    ctx.textAlign='center'; ctx.textBaseline='middle';
    ALAB.forEach(([a,cx,cy,tiles,dom,structs])=>{
      const nm=AREA_NAME(a,dom); if(!nm) return;
      const [sx,sy]=scr(AX(cx),AY(cy));
      if(sx<-60||sy<-20||sx>cv.width+60||sy>cv.height+20) return;
      const big=a===31, f=(big?13:11.5)*devicePixelRatio;
      ctx.font=`600 ${f}px sans-serif`;
      ctx.lineWidth=3*devicePixelRatio; ctx.strokeStyle='#0d1117cc';
      ctx.strokeText(nm,sx,sy); ctx.fillStyle=big?'#ffdf5d':'#e6edf3bb'; ctx.fillText(nm,sx,sy);
      if(structs&&zoom>0.16){
        ctx.font=`${9.5*devicePixelRatio}px sans-serif`;
        ctx.strokeText(structs+' structures',sx,sy+f+2*devicePixelRatio);
        ctx.fillStyle='#8b949e'; ctx.fillText(structs+' structures',sx,sy+f+2*devicePixelRatio);
      }
    });
    ctx.textBaseline='alphabetic'; ctx.textAlign='left';
  }
  // ---- ghost ----
  if((tool==='ps'||tool==='fort')&&hover){
    const isFort=tool==='fort';
    const chk=validate(hover[0],hover[1],isFort);
    let color='#3fb950';
    if(!chk.ok) color='#f85149';
    else{
      const extras=plan.map(p=>({x:p.x,y:p.y,fort:p.fort})).concat([{x:hover[0],y:hover[1],fort:isFort}]);
      if(!powerOf(D.myAid,extras).get(extras[extras.length-1])) color='#d29922';
    }
    ctx.globalAlpha=.85;
    ctx.beginPath(); bodyTiles(hover[0],hover[1],isFort).forEach(([bx,by])=>tilePath(bx,by,0.95));
    ctx.fillStyle=color+'55'; ctx.fill(); ctx.strokeStyle=color; ctx.lineWidth=2; ctx.stroke();
    ctx.strokeStyle=color+'99'; ctx.lineWidth=1.4; strokeZone(hover[0],hover[1],isFort);
    ctx.globalAlpha=1;
    drawIcon(isFort?'fort':'ps',hover[0],hover[1],{alpha:.7});
  }
}
function strokeZone(x,y,isFort){
  // true zone boundary: outer edge of the corner tiles, not their centres
  const b=zoneBoxUV(x,y,isFort);
  // corner order below is WEST, SOUTH, EAST, NORTH - each must be pushed out along its
  // own direction or the outline shears (it used to be off by one position, which drew
  // a skewed rectangle around a square zone)
  const c=[xy(b[0],b[2]),xy(b[1],b[2]),xy(b[1],b[3]),xy(b[0],b[3])];
  const hw=TW/2*zoom*devicePixelRatio, hh=TH/2*zoom*devicePixelRatio;
  const off=[[-hw,0],[0,hh],[hw,0],[0,-hh]];
  ctx.beginPath();
  c.forEach((t,i)=>{
    const [wx,wy]=px(t[0],t[1]); const [sx,sy]=scr(wx,wy);
    const p=[sx+off[i][0],sy+off[i][1]];
    i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]);
  });
  ctx.closePath(); ctx.stroke();
}

// ---- interaction ----
let dragging=false,lx=0,ly=0,moved=false,drawing=false,erasing=false;
let eraseHits={}, eraseCursor=null;
cv.addEventListener('mousedown',e=>{
  if(tool==='erase'){
    const r=cv.getBoundingClientRect();
    erasing=true; eraseHits={}; eraseSweep(tilePointAt(e.clientX-r.left, e.clientY-r.top)); return;
  }
  if(tool==='draw'){
    const r=cv.getBoundingClientRect();
    inkPath=[tilePointAt(e.clientX-r.left, e.clientY-r.top)];
    drawing=true; return;
  }
  dragging=true;moved=false;lx=e.clientX;ly=e.clientY;
});
window.addEventListener('mouseup',(e)=>{
  if(erasing){ erasing=false; eraseCommit(); return; }
  if(drawing){
    drawing=false;
    if(inkPath.length>1) pushOps([{op:'stroke', pts:inkPath, color:inkColor, width:inkWidth}],
                                 (applied)=>({op:'strokeDel', id:(applied[0]||{}).id}));
    inkPath=[]; draw(); return;
  }
  if(dragging&&!moved&&tool==='note'&&hover){
    const r=cv.getBoundingClientRect();
    addNoteAt.apply(null, tilePointAt(lx-r.left, ly-r.top));
    dragging=false; return;
  }
  if(dragging&&!moved&&tool==='pan'&&hover){
    const r=cv.getBoundingClientRect();
    const [tx,ty]=tilePointAt(lx-r.left, ly-r.top);
    const it=planAt(tx,ty);
    if(it){ openItemEditor(it); dragging=false; return; }
    const n=noteAt(tx,ty,2);
    if(n){ openNote(n); dragging=false; return; }
    const f=ourFortAt(tx,ty);
    if(f){ openFortEditor(f); dragging=false; return; }
    closeItemEditor();
  }
  if(dragging&&!moved&&(tool==='ps'||tool==='fort')&&hover){
    // tapping something already planned means "edit that", not "refuse the placement"
    const already=planAt(hover[0],hover[1]);
    if(already){ openItemEditor(already); dragging=false; return; }
    const isFort=tool==='fort';
    const chk=validate(hover[0],hover[1],isFort);
    if(chk.ok){
      pushOps([{op:'add', kind:isFort?'fort':'ps', x:hover[0], y:hover[1], alli:planAlli}],
              (applied)=>({op:'del', id:(applied[0]||{}).id}));
    } else flash('Cannot place: '+chk.reason);
  }
  dragging=false;
});
// exact (fractional) tile position under a canvas point — notes and ink are
// free-floating, so they must not snap to the lattice
function tilePointAt(mx,my){
  const wx=mx/zoom+ox, wy=my/zoom+oy;
  return [wx/(TW/2)+X0, wy/(TH/2)+Y0];
}
// nearest lattice tile to a canvas-space point (shared by hover and tap)
function tileAt(mx,my){
  const wx=mx/zoom+ox, wy=my/zoom+oy;
  const gx=Math.round(wx/(TW/2))+X0, gy=Math.round(wy/(TH/2))+Y0;
  let best=null,bd=1e9;
  for(let cx=gx-2;cx<=gx+2;cx++)for(let cy=gy-1;cy<=gy+1;cy++){
    if(((cx%2+2)%2)!==((cy%2+2)%2)) continue;
    const [twx,twy]=px(cx,cy); const d=(twx-wx)**2+((twy-wy)*(TW/TH))**2;
    if(d<bd){bd=d;best=[cx,cy];}
  }
  return best;
}
// The game's own numbers for an objective building, read out of kvk_building and
// localised by the client (LocalManager.LOCAL.getText / LocalUtils.getBuffShow).
const KINDS = D.kinds || {};
function kindOf(f){ return KINDS[f.bt+':'+f.name] || null; }
function hms(sec){
  sec = +sec || 0;
  if(!sec) return '';
  const h=Math.floor(sec/3600), m=Math.round(sec%3600/60);
  return h ? (h+'h'+(m?' '+m+'m':'')) : (m+'m');
}
function kindLines(f){
  const k = kindOf(f); if(!k) return [];
  const out = [];
  if(k.buff && k.buff!=='None') out.push('<span style="color:#3fb950">Buff:</span> '+k.buff);
  if(k.honor){
    const h = String(k.honor).split('|');
    out.push('<span style="color:#d2a8ff">Honor:</span> '+h[0]+'/h to the holder'
             + (h[1]&&h[1]!==h[0] ? ' ('+h[1]+' alliance)' : ''));
  }
  if(k.cap) out.push('Garrison capacity '+(+k.cap).toLocaleString());
  if(k.firstCondition) out.push('First conquest: hold '+hms(k.firstCondition)+' for the bonus reward');
  if(k.openCycle) out.push('Open cycle '+hms(k.openCycle)+(k.defenseCycle?' &middot; defence '+hms(k.defenseCycle):''));
  if(k.armySpeed) out.push('March speed effect '+k.armySpeed);
  if(k.durable) out.push('Durability '+(+k.durable).toLocaleString());
  if(k.desc && k.desc!==k.name) out.push('<span style="color:#8b949e">'+k.desc+'</span>');
  return out;
}
// one-line description of a tile, for the tap toast on touch devices
function tileSummary(t){
  const i=inCrop(t[0],t[1])?idx(t[0],t[1]):-1;
  const s=S.find(s=>bodyTiles(s.x,s.y,s.fort).some(([bx,by])=>bx===t[0]&&by===t[1]));
  if(s) return (s.fort?'Fort':'PS')+' '+tagOf(s.owner)+' S'+(ASRV[s.owner]||'?')+' · '+t[0]+';'+t[1]
    + (s.fort&&isPickedUp(s.x,s.y)?' · marked to be picked up':'');
  const f=FIX.find(f=>bodyTilesW(f.X,f.Y,f.w||2).some(([bx,by])=>bx===t[0]&&by===t[1]));
  if(f){
    const k=kindOf(f);
    return f.name+' '+f.X+';'+f.Y+(f.tag?' ['+f.tag+']':' (unowned)')
      + (k&&k.buff&&k.buff!=='None' ? ' · '+k.buff.replace(/<[^>]+>/g,'') : '')
      + (k&&k.honor ? ' · '+String(k.honor).split('|')[0]+' honor/h' : '');
  }
  if(i<0) return t[0]+';'+t[1];
  if(gBlock[i]) return 'Mountain · '+t[0]+';'+t[1];
  if(gJump[i]) return 'Wall-jump landing tile · '+t[0]+';'+t[1];
  if(gJumpW[i]) return 'Wall-jump west spot · '+t[0]+';'+t[1];
  if(gClaim[i]) return tagOf(aidOfIdx[gClaim[i]])+' territory · '+t[0]+';'+t[1];
  if(gExcl[i]) return 'Fixed-building zone · '+t[0]+';'+t[1];
  return 'Open ground · '+t[0]+';'+t[1];
}
cv.addEventListener('mousemove',e=>{
  const r=cv.getBoundingClientRect();
  if(erasing){ eraseSweep(tilePointAt(e.clientX-r.left, e.clientY-r.top)); draw(); return; }
  if(drawing){
    const p=tilePointAt(e.clientX-r.left, e.clientY-r.top);
    const last=inkPath[inkPath.length-1];
    if(!last || Math.abs(p[0]-last[0])+Math.abs(p[1]-last[1]) > 0.35) inkPath.push(p);
    draw(); return;
  }
  if(tool==='erase'){ eraseCursor=tilePointAt(e.clientX-r.left, e.clientY-r.top); draw(); }
  if(dragging){
    const dx=e.clientX-lx, dy=e.clientY-ly;
    if(Math.abs(dx)+Math.abs(dy)>3) moved=true;
    ox-=dx/zoom; oy-=dy/zoom; lx=e.clientX; ly=e.clientY; draw();
  }
  const best=tileAt(e.clientX-r.left, e.clientY-r.top);
  hover=best;
  document.getElementById('coord').textContent = best? best[0]+';'+best[1] : '-';
  updateTip(e,best);
  if(tool!=='pan'||dragging) draw();
});
// ---- touch: one finger pans, two fingers pinch-zoom, a tap places or inspects.
// The canvas sets touch-action:none so the browser never steals the gesture.
let tPts = new Map(), tPinch = null, tMoved = false, tStart = 0;
function tXY(t){ const r=cv.getBoundingClientRect(); return [t.clientX-r.left, t.clientY-r.top]; }
function zoomAt(mx,my,factor){
  const wx=mx/zoom+ox, wy=my/zoom+oy;
  zoom=Math.max(.06,Math.min(8,zoom*factor));
  ox=wx-mx/zoom; oy=wy-my/zoom; draw();
}
cv.addEventListener('touchstart',e=>{
  e.preventDefault();
  for(const t of e.changedTouches) tPts.set(t.identifier, tXY(t));
  if(tPts.size===1){ tMoved=false; tStart=Date.now();
    const p0=[...tPts.values()][0];
    if(tool==='draw'){ inkPath=[tilePointAt.apply(null,p0)]; drawing=true; }
    if(tool==='erase'){ erasing=true; eraseHits={}; eraseSweep(tilePointAt.apply(null,p0)); } }
  if(tPts.size>1 && drawing){ drawing=false; inkPath=[]; }   // second finger => pinch, not ink
  if(tPts.size===2){
    const [a,b]=[...tPts.values()];
    tPinch={d:Math.hypot(a[0]-b[0],a[1]-b[1]), mid:[(a[0]+b[0])/2,(a[1]+b[1])/2]};
  }
},{passive:false});
cv.addEventListener('touchmove',e=>{
  e.preventDefault();
  const prev=new Map(tPts);
  for(const t of e.changedTouches) if(tPts.has(t.identifier)) tPts.set(t.identifier, tXY(t));
  if(tPts.size===1 && erasing){
    eraseSweep(tilePointAt.apply(null,[...tPts.values()][0])); tMoved=true; draw();
  } else if(tPts.size===1 && drawing){
    const p=tilePointAt.apply(null,[...tPts.values()][0]);
    const last=inkPath[inkPath.length-1];
    if(!last || Math.abs(p[0]-last[0])+Math.abs(p[1]-last[1]) > 0.35) inkPath.push(p);
    tMoved=true; draw();
  } else if(tPts.size===1){
    const id=[...tPts.keys()][0], p0=prev.get(id), p1=tPts.get(id);
    const dx=p1[0]-p0[0], dy=p1[1]-p0[1];
    if(Math.abs(dx)+Math.abs(dy)>4) tMoved=true;
    ox-=dx/zoom; oy-=dy/zoom; draw();
  } else if(tPts.size>=2 && tPinch){
    const [a,b]=[...tPts.values()];
    const d=Math.hypot(a[0]-b[0],a[1]-b[1]);
    const mid=[(a[0]+b[0])/2,(a[1]+b[1])/2];
    if(tPinch.d>8){ zoomAt(mid[0],mid[1], d/tPinch.d); }
    tPinch={d:d, mid:mid}; tMoved=true;
  }
},{passive:false});
cv.addEventListener('touchend',e=>{
  e.preventDefault();
  const wasOne = tPts.size===1;
  const pt = wasOne ? [...tPts.values()][0] : null;
  for(const t of e.changedTouches) tPts.delete(t.identifier);
  if(tPts.size<2) tPinch=null;
  if(erasing){ erasing=false; eraseCommit(); return; }
  if(drawing){
    drawing=false;
    if(inkPath.length>1) pushOps([{op:'stroke', pts:inkPath, color:inkColor, width:inkWidth}],
                                 (applied)=>({op:'strokeDel', id:(applied[0]||{}).id}));
    inkPath=[]; draw(); return;
  }
  if(wasOne && !tMoved && pt && Date.now()-tStart<600 && (tool==='note'||tool==='pan')){
    const [fx,fy]=tilePointAt(pt[0],pt[1]);
    const n=noteAt(fx,fy,2.5);
    const it=planAt(fx,fy);
    if(tool==='pan' && it){ openItemEditor(it); return; }
    if(tool==='note'){ addNoteAt(fx,fy); return; }
    if(n){ openNote(n); return; }
    if(tool==='pan'){ const f=ourFortAt(fx,fy); if(f){ openFortEditor(f); return; } }
  }
  if(wasOne && !tMoved && pt && Date.now()-tStart<600){
    // a tap: snap to the tile under the finger, then place or just inspect it
    const t = tileAt(pt[0], pt[1]);
    hover = t;
    document.getElementById('coord').textContent = t ? t[0]+';'+t[1] : '-';
    if(t && (tool==='ps'||tool==='fort')){
      const already=planAt(t[0],t[1]);
      if(already){ openItemEditor(already); draw(); return; }
      const isFort = tool==='fort';
      const chk = validate(t[0],t[1],isFort);
      if(chk.ok) pushOps([{op:'add', kind:isFort?'fort':'ps', x:t[0], y:t[1], alli:planAlli}],
                         (applied)=>({op:'del', id:(applied[0]||{}).id}));
      else flash('Cannot place: '+chk.reason);
    } else if(t){
      flash(tileSummary(t));
    }
    draw();
  }
},{passive:false});
cv.addEventListener('touchcancel',()=>{ tPts.clear(); tPinch=null; },{passive:false});

// ---- zoom pad (mouse + touch)
document.getElementById('zIn').onclick =()=>zoomAt(cv.clientWidth/2, cv.clientHeight/2, 1.4);
document.getElementById('zOut').onclick=()=>zoomAt(cv.clientWidth/2, cv.clientHeight/2, 1/1.4);
document.getElementById('zFit').onclick=fit;
// ---- the panel is a slide-up sheet on narrow screens
let sheetSetOpen = ()=>{};                    // the More flyout closes the sheet through this
(function(){
  const btn=document.getElementById('sheetBtn'), side=document.getElementById('side'),
        grab=document.getElementById('sheetGrab');
  const setOpen=(open)=>{
    side.classList.toggle('open',open);
    // body class, not a sibling selector: #side is nested in #wrap, the button is not
    document.body.classList.toggle('sheetOpen',open);
    side.style.transform=''; side.style.transition='';   // drop any drag-in-progress offset
    btn.innerHTML = open ? 'Map &#9660;' : 'Info &#9650;';
    if(open){ const p=document.getElementById('morePanel');   // never stack two sheets
      p.classList.remove('open'); document.getElementById('moreBtn').innerHTML='More &#9662;'; }
  };
  sheetSetOpen = setOpen;
  btn.onclick=()=>setOpen(!side.classList.contains('open'));
  // drag the handle down to dismiss; the sheet follows your finger, and a tap closes it too
  let y0=null, dy=0;
  grab.addEventListener('pointerdown',e=>{
    y0=e.clientY; dy=0; side.style.transition='none';
    try{ grab.setPointerCapture(e.pointerId); }catch(err){}
  });
  grab.addEventListener('pointermove',e=>{
    if(y0===null) return;
    dy=Math.max(0,e.clientY-y0);
    side.style.transform='translateY('+dy+'px)';
  });
  const settle=()=>{                          // let the CSS transition finish the motion
    if(y0===null) return false;
    y0=null; side.style.transition='';
    if(dy>60){ setOpen(false); return true; }
    side.style.transform='';
    return false;
  };
  grab.addEventListener('pointerup',()=>{ const tap=dy<6; if(!settle() && tap) setOpen(false); });
  grab.addEventListener('pointercancel',settle);
  document.addEventListener('keydown',e=>{
    if(e.key==='Escape' && side.classList.contains('open')) setOpen(false); });
})();
cv.addEventListener('wheel',e=>{
  e.preventDefault();
  const r=cv.getBoundingClientRect();
  zoomAt(e.clientX-r.left, e.clientY-r.top, e.deltaY<0?1.15:0.87);
},{passive:false});

function updateTip(e,t){
  const tip=document.getElementById('tip');
  if(!t){tip.style.display='none';return;}
  const i=inCrop(t[0],t[1])?idx(t[0],t[1]):-1;
  const bits=[];
  const s=S.find(s=>bodyTiles(s.x,s.y,s.fort).some(([bx,by])=>bx===t[0]&&by===t[1]));
  if(s){
    const powered=powerByAid[s.owner]?powerByAid[s.owner].get(s):true;
    bits.push(`<b>${s.fort?'Alliance Fort':'Power Station'}</b> &middot; ${tagOf(s.owner)} <span style="color:#8b949e">S${ASRV[s.owner]||'?'}</span> &middot; ${s.st===2?'under construction':'built'}`
      + (s.st===3?(powered?' &middot; powered':' &middot; <span style="color:#f85149">NO POWER (predicted)</span>'):'') + ` &middot; ${s.x};${s.y}`);
  }
  const f=FIX.find(f=>bodyTilesW(f.X,f.Y,f.w||2).some(([bx,by])=>bx===t[0]&&by===t[1]));
  if(f){
    bits.push(`<b>${f.name}</b> ${f.X};${f.Y} &middot; ${f.tag?('held by '+f.tag+' (S'+f.sid+')'):'<span style="color:#d29922">unowned</span>'}`);
    kindLines(f).forEach(l=>bits.push(l));
  }
  if(i>=0){
    if(gJump[i]) bits.push('<span style="color:#d2a8ff">wall-jump landing tile</span>');
    if(gBlock[i]) bits.push('Blocked terrain');
    if(gExcl[i]) bits.push('Fixed-building zone (no build)');
    if(gClaim[i]) bits.push(tagOf(aidOfIdx[gClaim[i]])+' territory');
    if(gPlanClaim[i]) bits.push('Planned zone');
    if(gLegalV[i]&&!gClaim[i]&&!gBlock[i]) bits.push('<span style="color:#3fb950">verified placeable in game</span>');
  }
  if(!bits.length){tip.style.display='none';return;}
  tip.innerHTML=bits.join('<br>');
  tip.style.display='block';
  tip.style.left=Math.min(e.clientX+14, innerWidth-270)+'px';
  tip.style.top=(e.clientY+14)+'px';
}
let flashT=null;
function flash(msg){
  const tip=document.getElementById('tip');
  tip.innerHTML='<span style="color:#f85149">'+msg+'</span>';
  tip.style.display='block';
  clearTimeout(flashT); flashT=setTimeout(()=>tip.style.display='none',2000);
}

// ---- side panel ----
function counts(){
  const c=new Array(D.alliances.length+1).fill(0);
  for(let i=0;i<N;i++) if(gClaim[i]) c[gClaim[i]]++;
  const mine=S.filter(s=>s.owner===D.myAid);
  const built=mine.filter(s=>!s.fort&&s.st===3);
  const act=built.filter(s=>powerByAid[D.myAid].get(s));
  const tiles=(tag)=>{ const a=Object.keys(TAG).find(k=>TAG[k]===tag); return a?c[AIDN[a]].toLocaleString():'-'; };
  document.getElementById('sDog').textContent=tiles('Dog*');
  document.getElementById('sMss').textContent=tiles('MSS*');
  document.getElementById('sCat').textContent=tiles('Cat+');
  renderWorld(c);
  document.getElementById('sAct').textContent=act.length+' / '+built.length;
  document.getElementById('sBld').textContent=mine.filter(s=>s.st===2).length;
  renderForts();                       // owns #sFort too, so it can't drift from the panel
  const cap=D.live.psCapBase+D.live.psCapBuff;
  document.getElementById('sPsCap').textContent=D.live.psBuilt+' / '+cap;
  const okRank=D.live.psJurisdiction.split(';').indexOf(String(D.live.rank))>=0;
  const el=document.getElementById('sRank');
  el.textContent='rank '+D.live.rank+(okRank?' can build':' CANNOT build');
  el.style.color=okRank?'var(--green)':'var(--red)';
}
// ---- whole-map panels: warzones, objectives, navigation ----
const OBJ_NAME={3:'Expedition Outpost',4:'Expedition Base',5:'Arsenal / Military Base',
                6:'Military Fortress',7:'Research Facility',8:'Eternal City',9:'Gate',10:'Molten Ark'};
function renderWorld(claimCounts){
  // per-server rollup
  const srv={};
  S.forEach(s=>{
    const sid=ASRV[s.owner]||0;
    const r=srv[sid]||(srv[sid]={ps:0,fort:0,tiles:0,tags:new Set()});
    s.fort?r.fort++:r.ps++; r.tags.add(tagOf(s.owner));
  });
  D.alliances.forEach((a,i)=>{ const sid=a[3]; if(srv[sid]) srv[sid].tiles+=claimCounts[i+1]||0; });
  const rows=Object.keys(srv).map(k=>[+k,srv[k]]).sort((a,b)=>(b[1].ps+b[1].fort)-(a[1].ps+a[1].fort));
  const el=document.getElementById('srvTable'); el.innerHTML='';
  rows.forEach(([sid,r])=>{
    const div=document.createElement('div'); div.className='stat';
    const mine=sid===2864;
    div.innerHTML=`<span><span class="sw" style="background:${D.srvColor[sid]||'#8b949e'};border-color:${D.srvColor[sid]||'#8b949e'}"></span>`
      +`<b style="${mine?'color:var(--green)':''}">S${sid}</b> <span style="color:var(--muted)">${[...r.tags].sort().join(' ')}</span></span>`
      +`<b>${r.ps+r.fort} <span style="color:var(--muted);font-weight:400">(${r.fort}f)</span></b>`;
    el.appendChild(div);
  });
  // ---- other warzones' crossings, grouped by server
  var at=document.getElementById('altTable'); at.innerHTML='';
  var bySid={};
  ALT.forEach(function(a){ (bySid[a.sid]=bySid[a.sid]||[]).push(a); });
  Object.keys(bySid).map(Number).sort(function(a,b){
    return bySid[b].reduce(function(n,x){return n+x.pairs;},0) - bySid[a].reduce(function(n,x){return n+x.pairs;},0);
  }).forEach(function(sid){
    var list=bySid[sid];
    var tiles={}; list.forEach(function(a){ (a.sample||[]).forEach(function(p){ tiles[p[2]+';'+p[3]]=1; }); });
    var tags={}; list.forEach(function(a){ (a.tags||[]).forEach(function(t){ tags[t]=1; }); });
    var div=document.createElement('div'); div.className='jrow'; div.style.borderLeftColor=D.srvColor[sid]||'#f0883e';
    div.innerHTML='<div class="t" style="color:'+(D.srvColor[sid]||'#f0883e')+'">S'+sid+' &middot; '+list.length+' of 4 gates</div>'
      +'<div class="d">'+Object.keys(tiles).length+' landing tiles &middot; '+Object.keys(tags).join(' ')+'<br>'
      +list.map(function(a){ return 'gate '+a.gate[0]+';'+a.gate[1]+' &rarr; '+a.best.target[0]+';'+a.best.target[1]; }).join('<br>')+'</div>';
    div.onclick=function(){ var b=list[0].best; flyTo(Math.round((b.home[0]+b.target[0])/2), b.home[1], 1.3); };
    at.appendChild(div);
  });
  document.getElementById('altNote').innerHTML =
    'Turn on <b>Other warzones</b> to draw these: <span style="color:#39c5cf">cyan = their side</span>, '
    + '<span style="color:#f0883e">orange = where they land</span>. Surveyed within 34 tiles of each gate using the '
    + 'same rules as ours, but <b>not</b> oracle-verified &mdash; treat them as estimates. '
    + 'All 12 Lv.2 and 8 Lv.3 gates show nothing yet because no alliance has a powered network in the mid or inner '
    + 'rings to jump from; they open up the moment someone establishes one. '
    + DEAD.length + ' walkable pockets have no gate at all ('
    + DEAD.reduce(function(n,p){return n+p.tiles;},0).toLocaleString() + ' tiles) &mdash; nobody can operate there.';
  document.getElementById('srvNote').innerHTML=
    `${S.length.toLocaleString()} structures, ${D.alliances.length} alliances, ${rows.length} warzones &mdash; harvested from a 159-stop entity sweep of the whole map. `
    +`Ours is <b style="color:var(--green)">S2864</b>. Other servers' per-alliance splits are live from the same sweep; only S2864's power state is authoritative.`;
  // objectives
  const ot=document.getElementById('objTable'); ot.innerHTML='';
  const byType={};
  FIX.forEach(f=>{ const t=byType[f.bt]||(byType[f.bt]={n:0,owned:0}); t.n++; if(f.sid) t.owned++; });
  Object.keys(byType).sort((a,b)=>a-b).forEach(bt=>{
    const t=byType[bt], div=document.createElement('div'); div.className='stat';
    div.innerHTML=`<span>${OBJ_NAME[bt]||('type '+bt)}</span>`
      +`<b>${t.owned?`<span class="ok">${t.owned}</span>`:'<span class="warn">0</span>'} / ${t.n}</b>`;
    ot.appendChild(div);
  });
}
function buildNav(){
  const sel=document.getElementById('nav');
  const opts=[['','Jump to\u2026'],['home','Our zone 1 (Dog*)'],
              ['north','Zone 1 north (S2501)'],['mid','Past our gates (mid ring)'],
              ['g836','Our gate 128;836'],['g904','Our gate 128;904'],
              ['g988','Our gate 128;988'],['g1094','Our gate 128;1094']];
  ALAB.slice().sort((a,b)=>b[5]-a[5]).forEach(([a,cx,cy,tiles,dom,structs])=>{
    const nm=AREA_NAME(a,dom); if(!nm) return;
    opts.push(['a'+a, (a===31?'':(a<11?'Warzone ':'')) + nm + (structs?` (${structs})`:'') ]);
  });
  FIX.filter(f=>[5,6,7,8,10].indexOf(f.bt)>=0).sort((a,b)=>a.bt-b.bt).forEach(f=>
    opts.push(['f'+f.X+','+f.Y, f.name+' '+f.X+';'+f.Y]));
  sel.innerHTML=opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
  sel.onchange=()=>{
    const v=sel.value; if(!v) return;
    if(v==='home'){ flyTo(60,1000,1.1); }
    else if(v==='north'){ flyTo(60,600,1.0); }
    else if(v==='mid'){ flyTo(160,900,0.9); }
    else if(v[0]==='g'&&/^g\d+$/.test(v)){ flyTo(132, +v.slice(1), 2.2); }
    else if(v[0]==='a'){ const a=ALAB.find(l=>l[0]===+v.slice(1));
      if(a) flyTo(Math.round(a[1]*2), Math.round(a[2]*2), a[0]===31?0.9:0.5); }
    else if(v[0]==='f'){ const [x,y]=v.slice(1).split(',').map(Number); flyTo(x,y,1.6); }
    sel.value='';
  };
}
function renderPlan(){
  const el=document.getElementById('plan'); el.innerHTML='';
  const pp=planPowered();
  let tiles=0,cost=0,time=0;
  const claimed=new Set();
  for(let i=0;i<N;i++) if(gClaim[i]) claimed.add(i);   // mountains inside a zone ARE claimed
  plan.forEach((p,i)=>{
    zoneTiles(p.x,p.y,p.fort).forEach(([x,y])=>{ if(inCrop(x,y)){const j=idx(x,y); if(!claimed.has(j)){claimed.add(j);tiles++;}} });
    cost+=p.fort?10000:500; time+=p.fort?3:2;
    const div=document.createElement('div'); div.className='planitem';
    const col = p.alli==='MSS*'?'#388bfd':(p.alli==='Cat+'?'#d29922':'#3fb950');
    div.dataset.i = i;
    div.innerHTML=`<span>#${i+1} ${p.fort?'Fort':'PS'} @ <b>${p.x};${p.y}</b> `
      +`<button type="button" class="pa" data-i="${i}" style="background:${col}22;border:1px solid ${col};color:${col};border-radius:4px;font-size:10px;padding:1px 5px;cursor:pointer" title="Tap to change alliance">${p.alli||'Dog*'}</button> `
      +`<span class="${pp.get(p)?'ok':'warn'}">${pp.get(p)?'powered':'no power (predicted)'}</span>`
      +(p.by?` <span style="color:var(--muted);font-size:10px">by ${esc(p.by)}</span>`:'')+`</span>`
      +`<span class="del" data-i="${i}" title="Delete this one">&times;</span>`;
    el.appendChild(div);
  });
  document.getElementById('pTiles').textContent=tiles.toLocaleString();
  document.getElementById('pCost').textContent=cost.toLocaleString();
  document.getElementById('pTime').textContent=time+'h';
  document.getElementById('planEmpty').style.display=plan.length?'none':'block';
  el.querySelectorAll('.del').forEach(d=>d.onclick=(ev)=>{
    ev.stopPropagation();
    const p=plan[+d.dataset.i]; if(!p) return;
    pushOps([{op:'del', id:p.id}],
            ()=>({op:'add', kind:p.fort?'fort':'ps', x:p.x, y:p.y, alli:p.alli}));
  });
  el.querySelectorAll('.pa').forEach(b=>b.onclick=(ev)=>{
    ev.stopPropagation();
    const p=plan[+b.dataset.i]; if(!p) return;
    const cur=PLAN_ALLI.indexOf(p.alli||'Dog*'), to=PLAN_ALLI[(cur+1)%PLAN_ALLI.length], from=p.alli;
    pushOps([{op:'setAlli', id:p.id, alli:to}], ()=>({op:'setAlli', id:p.id, alli:from}));
  });
  el.querySelectorAll('.planitem').forEach(d=>d.onclick=()=>{
    const p=plan[+d.dataset.i]; if(p) flyTo(p.x,p.y,2.2);
  });
  counts();
}
function renderJumps(){
  const el=document.getElementById('jumps'); el.innerHTML='';
  if(!JUMPS.length){ el.innerHTML='<div class="note">No gate-reachable crossing in this snapshot.</div>'; return; }
  JUMPS.forEach((c,i)=>{
    const div=document.createElement('div'); div.className='jrow';
    const wk=c.westKind==='new'
      ? `<span class="warn">place a NEW PS at ${c.bestWest[0]};${c.bestWest[1]}</span>`
      : `from <b>${c.bestAnchor}</b>`;
    div.innerHTML=`<div class="t">${i+1}. y ${c.y0}&ndash;${c.y1} &middot; land ${c.best[0]};${c.best[1]}</div>`
      +`<div class="d">${wk}<br>`
      +`${c.tiles} landing tiles &middot; ${c.west.length} west spots &middot; wall x${c.wall[0]}&ndash;${c.wall[1]} (${c.thick} thick)<br>`
      +`gate ${c.gate[0]};${c.gate[1]} (${c.gateSteps} steps from the landing tile)</div>`;
    div.onclick=()=>flyTo(Math.round((c.best[0]+(c.bestWest?c.bestWest[0]:c.best[0]))/2),c.best[1],2.2);
    el.appendChild(div);
  });
  (D.jumps.gateNotes||[]).forEach(n=>{
    const div=document.createElement('div'); div.className='jrow';
    div.style.opacity=.75;
    div.innerHTML=`<div class="t">Gate ${n.gate[0]};${n.gate[1]} &middot; <span class="warn">no crossing for us</span></div>`
      +`<div class="d">${n.why}${n.westClaimedBy.length?' &mdash; '+n.westClaimedBy.map(o=>o[0]+' holds '+o[1]+' of the west tiles').join(', '):''}</div>`;
    div.onclick=()=>flyTo(n.gate[0],n.gate[1],2.0);
    el.appendChild(div);
  });
}
function flyTo(x,y,z){
  closeItemEditor();
  zoom=z||2.2;
  const [wx,wy]=px(x,y);
  ox=wx-cv.clientWidth/2/zoom; oy=wy-cv.clientHeight/2/zoom;
  draw();
}
// local copy is only a cache for a quick first paint / offline glance; the worker
// document is the source of truth
function savePlan(){ try{ localStorage.setItem('elSimPlan4',JSON.stringify({snapshot:D.snapshot,items:plan})); }catch(e){} }
function setTool(t){
  tool=t;
  [['toolPan','pan'],['toolPS','ps'],['toolFort','fort'],['toolNote','note'],['toolDraw','draw'],['toolErase','erase']]
    .forEach(([id,name])=>{ const b=document.getElementById(id); if(b) b.classList.toggle('active',t===name); });
  cv.classList.toggle('placing',t!=='pan');
  const bar=document.getElementById('inkbar');
  // visibility, not display: showing the palette must not resize the header and
  // shove the map out from under your finger
  if(bar) bar.style.visibility=(t==='draw'||t==='note')?'visible':'hidden';
}
document.getElementById('toolPan').onclick=()=>setTool('pan');
document.getElementById('toolPS').onclick=()=>setTool('ps');
document.getElementById('toolFort').onclick=()=>setTool('fort');
document.getElementById('toolNote').onclick=()=>setTool('note');
document.getElementById('toolDraw').onclick=()=>setTool('draw');
document.getElementById('toolErase').onclick=()=>setTool('erase');
(function(){                                  // colour + width picker for ink and notes
  const bar=document.getElementById('inkbar');
  INK.forEach(c=>{
    const b=document.createElement('span'); b.className='swatch'+(c===inkColor?' on':'');
    b.style.background=c; b.title=c; b.dataset.c=c;
    b.onclick=()=>{ inkColor=c; try{localStorage.setItem('elSimInk',c);}catch(e){}
      bar.querySelectorAll('.swatch').forEach(x=>x.classList.toggle('on',x.dataset.c===c)); };
    bar.appendChild(b);
  });
  const w=document.createElement('input'); w.type='range'; w.min='1'; w.max='10'; w.value=String(inkWidth);
  w.style.width='62px'; w.title='Pen width';
  w.oninput=()=>{ inkWidth=+w.value; };
  bar.appendChild(w);
  bar.style.visibility='hidden';
})();
function tg(id,fn,on){
  const b=document.getElementById(id);
  if(on) b.classList.add('active');
  b.onclick=()=>{ b.classList.toggle('active'); fn(b.classList.contains('active')); lodDirty=true; draw(); };
}
tg('tgJump',v=>showJump=v,true);
tg('tgAlt',v=>showAlt=v,false);
tg('tgClaims',v=>showClaims=v,true);
tg('tgZones',v=>showZones=v,true);
tg('tgMtn',v=>showMtn=v,true);
tg('tgBlock',v=>showBlock=v,false);
tg('tgAreas',v=>showAreas=v,true);
tg('tgLegal',v=>showLegal=v,false);
tg('tgGridL',v=>showGrid=v,false);
document.getElementById('fit').onclick=fit;
(function(){                                  // More flyout (phone only; inline on desktop)
  const btn=document.getElementById('moreBtn'), panel=document.getElementById('morePanel');
  btn.onclick=(e)=>{ e.stopPropagation(); const on=panel.classList.toggle('open');
    btn.innerHTML = on ? 'More &#9652;' : 'More &#9662;';
    if(on) sheetSetOpen(false); };            // one panel over the map at a time
  // any choice inside closes it, so it never sits over the map
  panel.addEventListener('click', (e)=>{ if(e.target.tagName==='BUTTON'){
    panel.classList.remove('open'); btn.innerHTML='More &#9662;'; } });
  document.addEventListener('click',(e)=>{
    if(panel.classList.contains('open') && !panel.contains(e.target) && e.target!==btn){
      panel.classList.remove('open'); btn.innerHTML='More &#9662;'; }
  });
})();
(function(){
  const sel=document.getElementById('planAlli');
  sel.innerHTML=PLAN_ALLI.map(a=>`<option value="${a}"${a===planAlli?' selected':''}>for ${a}</option>`).join('');
  sel.onchange=()=>{ planAlli=sel.value; try{localStorage.setItem('elSimAlli',planAlli);}catch(e){} draw(); };
})();
syncUndoBtn();
document.getElementById('clearPlan').onclick=()=>{
  const what = prompt('Clear what? Type: plan, notes, strokes, or all','plan');
  if(!what) return;
  if(['plan','notes','strokes','all'].indexOf(what)<0) return flash('Unknown target');
  if(!confirm('Clear '+what+' for EVERYONE? This is the shared plan.')) return;
  pushOps([{op:'clear', what}]);
};
document.getElementById('undoBtn').onclick=undo;
window.addEventListener('keydown',e=>{
  if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){ e.preventDefault(); undo(); }
});
document.getElementById('copyPlan').onclick=()=>{
  const pp=planPowered();
  const lines=plan.map((p,i)=>`#${i+1} ${p.fort?'Alliance Fort':'Power Station'} @ ${p.x};${p.y}${pp.get(p)?'':' (WARNING: not connected to the fort chain)'}`);
  navigator.clipboard.writeText('EL build plan - snapshot '+D.snapshot+'\n'+lines.join('\n')).then(()=>flash('Plan copied'));
};
function fit(){
  const cssW=cv.clientWidth, cssH=cv.clientHeight;
  const wpx=W*TW/2, hpx=H*TH/2;
  zoom=Math.min(cssW/wpx,cssH/hpx)*0.96;
  ox=-(cssW/zoom-wpx)/2; oy=-(cssH/zoom-hpx)/2;
  draw();
}
// ---- self test: does the captured terrain line up with the blocked-tile mask? ----
window.__st = function(){
  const out={corridors:JUMPS.length, east:0, west:0, needNewPS:0,
             forts:PLAN_ALLI.map(a=>{ const b=fortBudget(a);
               return a+' '+(b.built+b.planned)+'/'+b.cap+(b.dropped?' (-'+b.dropped+')':''); }).join(' · '),
             fortsFree:PLAN_ALLI.map(a=>fortBudget(a).free).join('/'),
             structs:S.length, fixed:FIX.length, alliances:D.alliances.length,
             blocked:0, terrain:{world:!!TERR.world.im.naturalWidth, district:!!TERR.district.im.naturalWidth}};
  for(let i=0;i<N;i++) if(gBlock[i]) out.blocked++;
  JUMPS.forEach(c=>{ out.east+=c.east.length; out.west+=c.west.length; if(c.needsNewPS) out.needNewPS++; });
  let bad=0, badW=0;
  JUMPS.forEach(c=>{
    c.east.forEach(([x,y])=>{ if(!validate(x,y,false).ok) bad++; });
    c.west.forEach(([x,y])=>{ if(!validate(x,y,false).ok) badW++; });
  });
  out.eastFailing=bad; out.westFailing=badW;
  out.texExample = JUMPS.some(c=>c.east.some(([x,y])=>x===133&&y===791)) ? 'OK' : 'MISSING';
  // per-server rollup, so the whole-map harvest can be checked at a glance
  const srv={};
  S.forEach(s=>{ const k='S'+(ASRV[s.owner]||0); srv[k]=(srv[k]||0)+1; });
  out.byServer=srv;
  // does the captured terrain sit where the blocked mask says? (home district sheet;
  // rock art is desaturated, grass is not - saturation is the discriminator)
  const T=TERR.district;
  if(T.im.naturalWidth){
    const c=document.createElement('canvas'); c.width=T.w; c.height=T.h;
    const g=c.getContext('2d'); g.drawImage(T.im,0,0);
    const mx0=Math.floor(108*112/T.wpp), mw=Math.ceil(42*112/T.wpp);
    const im=g.getImageData(mx0,0,mw,T.h).data;
    const rockAt=(x,y)=>{
      const mx=Math.round(x*112/T.wpp)-mx0, my=Math.round((y-750)*81/T.wpp);
      if(mx<0||mx>=mw||my<0||my>=T.h) return null;
      const i=(my*mw+mx)*4, r=im[i], gg=im[i+1], b=im[i+2];
      return (Math.max(r,gg,b)-Math.min(r,gg,b)) < 75;
    };
    const score=(dx,dy)=>{
      let hit=0,miss=0,fp=0,open=0;
      for(let y=756;y<=1324;y++) for(let x=112;x<=148;x++){
        if((x+y)%2) continue;
        const r=rockAt(x,y); if(r===null) continue;
        const j=idx(x+dx,y+dy); if(j<0||j>=N) continue;
        if(gBlock[j]){ r?hit++:miss++; } else { r?fp++:open++; }
      }
      return {onRock:+(hit/(hit+miss)*100).toFixed(1), falseRock:+(fp/(fp+open)*100).toFixed(1)};
    };
    out.mask = {aligned: score(0,0), shiftX_minus4: score(-4,0), shiftX_plus4: score(4,0),
                shiftY_minus4: score(0,-4), shiftY_plus4: score(0,4)};
  }
  return out;
};
rebuildPlanGrids(); renderJumps(); buildNav(); renderPlan(); renderNotes(); renderClog();
resize(); fit(); setTool('pan');

// ---- shared plan: first load, one-time migration, then keep in step ----
(function(){
  const localItems = plan.slice();          // whatever was in localStorage before sharing existed
  pullPlan().then(()=>{
    if(!shareOK) return;
    const migrated = (function(){ try{ return localStorage.getItem('elSimMigrated')==='1'; }catch(e){ return true; } })();
    if(!migrated && localItems.length && !(SP.items||[]).length && whoAmI()){
      const ops = localItems.slice(0,50).map(p=>({op:'add', kind:p.fort?'fort':'ps', x:p.x, y:p.y, alli:p.alli||'Dog*'}));
      pushOps(ops).then(()=>{ try{ localStorage.setItem('elSimMigrated','1'); }catch(e){}
        flash('Moved your '+ops.length+' local placements into the shared plan'); });
    } else { try{ localStorage.setItem('elSimMigrated','1'); }catch(e){} }
  });
  // co-planners: refresh on a timer and whenever the tab comes back
  setInterval(()=>{ if(document.visibilityState==='visible' && !drawing) pullPlan(); }, 25000);
  window.addEventListener('focus', ()=>{ if(!drawing) pullPlan(); });
})();

window.__el = {flyTo:flyTo, fit:fit, render:render, zoomNow:()=>zoom, D:D, S:S, FIX:FIX, JUMPS:JUMPS, TERR:TERR, validate:validate, selftest:window.__st, fortBudget:fortBudget, ourFortAt:ourFortAt, SP:()=>SP, plan:()=>plan};
})();
