// EL Build Simulator app - generated by gen_el_sim3.py, do not edit by hand.
// Runs only after el-sim.html has fetched the gated payload into window.__EL_DATA.
(function(){

const D = window.__EL_DATA;
const [X0,X1,Y0,Y1] = D.crop;
const W = X1-X0+1, H = Y1-Y0+1;
const TW = 14, TH = 10.125;
const idx = (x,y)=> (y-Y0)*W + (x-X0);
const inCrop = (x,y)=> x>=X0&&x<=X1&&y>=Y0&&y<=Y1;
const uv = (x,y)=> [(x+y)/2,(x-y)/2];
const xy = (u,v)=> [u+v,u-v];
const N = W*H;

const ICONS_SRC = {"ps": "assets/el-sim/icon-ps.png", "fort": "assets/el-sim/icon-fort.png", "outpost": "assets/el-sim/icon-outpost.png", "base": "assets/el-sim/icon-base.png", "gate": "assets/el-sim/icon-gate.png", "mfort": "assets/el-sim/icon-mfort.png", "ark": "assets/el-sim/icon-ark.png", "research": "assets/el-sim/icon-research.png", "city": "assets/el-sim/icon-city.png"};
const ICONS = {};
Object.keys(ICONS_SRC).forEach(k=>{const im=new Image();im.onload=()=>draw();im.src=ICONS_SRC[k];ICONS[k]=im;});
// ---- terrain: one mosaic of the game's own render (see generator header) ----
const TERR_SRC = {"world":{"w":2688,"h":3888,"worldPerPx":32,"x0":0,"y0":0,"img":"assets/el-sim/world-mosaic.jpg"},"district":{"w":2464,"h":5873,"worldPerPx":8,"x0":0,"y0":750,"img":"assets/el-sim/district-mosaic.jpg"}};
// two sheets of the game's own render: the whole map at 32 world/px and the home
// district at 8. Each maps 1 mosaic px -> worldPerPx/16 display px, so both land on
// the tile lattice exactly; the finer sheet simply draws on top where it applies.
const TERR = {};
['world','district'].forEach(k=>{
  const t = TERR_SRC[k], im = new Image();
  im.onload = ()=>draw(); im.src = t.img;
  TERR[k] = {im, dx: t.x0*TW/2, dy: (t.y0-Y0)*TH/2,
             dw: t.w*t.worldPerPx/16, dh: t.h*t.worldPerPx/16, wpp: t.worldPerPx, w: t.w, h: t.h};
});

// ---- grids ----
const gBlock = new Uint8Array(N);
// whole-map blocked mask, unpacked from the 74 KB bitmask (1 bit per lattice tile,
// row-major over cols = 384 cells; tile x = col*2 + (y&1))
(function(){
  const bin = atob(D.mask.b64), cols = D.mask.cols;
  for(let y=0;y<D.mask.rows;y++){
    const par = y&1;
    for(let c=0;c<cols;c++){
      const i = y*cols+c;
      if(bin.charCodeAt(i>>3) & (1<<(i&7))){ const x=c*2+par; if(inCrop(x,y)) gBlock[idx(x,y)]=1; }
    }
  }
})();
const gLegalV = new Uint8Array(N);
D.legalV.forEach(s=>{const [x,y]=s.split(';').map(Number); if(inCrop(x,y)) gLegalV[idx(x,y)]=1;});
// alliance table: index 1..31 in the claim grid, colour by server (our own three keep
// their familiar green / blue / amber)
const AIDN = {}, CL = {}, TAG = {}, ANAME = {}, ASRV = {};
D.alliances.forEach((a,i)=>{ const n=i+1;
  AIDN[a[0]]=n; CL[n]=a[4]; TAG[a[0]]=a[1]; ANAME[a[0]]=a[2]; ASRV[a[0]]=a[3];
});
const tagOf = (aid)=> TAG[aid] || ('a'+aid);
const aidOfIdx = {}; D.alliances.forEach((a,i)=>aidOfIdx[i+1]=a[0]);

function zoneBoxUV(px,py,isFort){
  const [u0,v0]=uv(px,py);
  return isFort? [u0-4,u0+5,v0-5,v0+4] : [u0-3,u0+3,v0-3,v0+3];
}
function zoneTiles(px,py,isFort){
  const b=zoneBoxUV(px,py,isFort); const t=[];
  for(let u=b[0];u<=b[1];u++) for(let v=b[2];v<=b[3];v++) t.push(xy(u,v));
  return t;
}
function bodyTiles(px,py,isFort){
  return isFort? [[px,py],[px+1,py+1],[px-1,py+1],[px,py+2]] : [[px,py]];
}
function fixedBox(X,Y,w,lw){
  const l=X+1-lw, c=Y+w-1;
  const u0=(l+c)/2, v0=(l-c)/2;
  return [u0, u0+lw-1, v0, v0+lw-1];
}

const gClaim = new Uint8Array(N);   // alliance id number
const gExcl  = new Uint8Array(N);
const gBody  = new Uint8Array(N);
const S = D.structs.map((a,i)=>({x:a[0],y:a[1],fort:!!a[2],owner:a[3],st:a[4],st2:a[5],i,
                                 kind:'struct', depth:(a[1]-Y0)*TH/2}));
S.forEach(s=>{
  const an=AIDN[s.owner]; if(!an) return;
  zoneTiles(s.x,s.y,s.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gClaim[idx(x,y)]=an; });
  bodyTiles(s.x,s.y,s.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gBody[idx(x,y)]=1; });
});
// build_type -> sprite (from kvk_building.building_image)
const FIXICON = {3:'outpost',4:'base',5:'ps',6:'mfort',7:'research',8:'city',9:'gate',10:'ark'};
const FIX = D.fixed.map(f=>({X:f[0],Y:f[1],bt:f[2],w:f[3],lw:f[4],sid:f[5],tag:f[6],id:f[7],
                             name:f[8], kind:'fixed', depth:(f[1]-Y0)*TH/2}));
// gRing: the 1-tile border ring of a Lv.1 Gate WE own is placeable
// (checkPosEnableInKVK) even though the square is claimed. No gate is ours in this
// snapshot, so this is dormant but correct if one is captured.
const gRing = new Uint8Array(N);
FIX.forEach(f=>{
  const b=fixedBox(f.X,f.Y,f.w,f.lw);
  // integer bounds: (l+c) can be odd on some rows, which would put a naive
  // integer walk off-lattice
  const u0=Math.ceil(b[0]), u1=Math.floor(b[1]), v0=Math.ceil(b[2]), v1=Math.floor(b[3]);
  const ownGate = f.bt===9 && f.sid===2864;
  const an = AIDN[Object.keys(TAG).find(a=>TAG[a]===f.tag)] || 0;
  for(let u=u0;u<=u1;u++) for(let v=v0;v<=v1;v++){
    const [x,y]=xy(u,v); if(!inCrop(x,y)) continue;
    const i=idx(x,y);
    const onRing = (u===u0||u===u1||v===v0||v===v1);
    // an owned building carries a territory record, and the fixed-building square
    // is only consulted when a tile has NO record -> don't set gExcl for those
    if(f.sid){ if(!gClaim[i]) gClaim[i]=an; if(ownGate&&onRing) gRing[i]=1; }
    else gExcl[i]=1;
  }
  bodyTiles(f.X,f.Y,true).forEach(([x,y])=>{ if(inCrop(x,y)) gBody[idx(x,y)]=1; });
});

// ---- jump overlay: east landing tiles AND the west tiles that reach them ----
const gJump  = new Uint8Array(N);   // east side, past the wall
const gJumpW = new Uint8Array(N);   // west side, a PS here spans the wall
const JUMPS = D.jumps.corridors || [];
JUMPS.forEach(c=>{
  (c.east||[]).forEach(([x,y])=>{ if(inCrop(x,y)) gJump[idx(x,y)]=1; });
  (c.west||[]).forEach(([x,y])=>{ if(inCrop(x,y)) gJumpW[idx(x,y)]=1; });
});

// ---- power ----
function boxesTouch(b1,b2){
  const du=Math.max(b1[0]-b2[1],b2[0]-b1[1],0);
  const dv=Math.max(b1[2]-b2[3],b2[2]-b1[3],0);
  return du<=1 && dv<=1 && !(du===1&&dv===1);
}
function powerOf(aid, extra){
  const list=S.filter(s=>s.owner===aid&&s.st===3).map(s=>({box:zoneBoxUV(s.x,s.y,s.fort),fort:s.fort,ref:s}));
  (extra||[]).forEach(p=>list.push({box:zoneBoxUV(p.x,p.y,p.fort),fort:p.fort,ref:p}));
  const n=list.length, adj=Array.from({length:n},()=>[]);
  for(let i=0;i<n;i++)for(let j=i+1;j<n;j++) if(boxesTouch(list[i].box,list[j].box)){adj[i].push(j);adj[j].push(i);}
  const pw=new Set(), st=[];
  list.forEach((m,i)=>{ if(m.fort){pw.add(i);st.push(i);} });
  while(st.length){const k=st.pop(); adj[k].forEach(nb=>{if(!pw.has(nb)){pw.add(nb);st.push(nb);}});}
  const map=new Map(); list.forEach((m,i)=>map.set(m.ref,pw.has(i))); return map;
}
const powerByAid={};
Object.keys(AIDN).forEach(k=>{ powerByAid[k]=powerOf(+k,null); });

// ---- plan ----
let plan=[];
try{
  const st=JSON.parse(localStorage.getItem('elSimPlan4')||'null');
  const items=st&&Array.isArray(st.items)?st.items:(Array.isArray(st)?st:[]);
  plan=items.filter(p=>p&&Number.isInteger(p.x)&&Number.isInteger(p.y)&&(p.x+p.y)%2===0&&typeof p.fort==='boolean');
  if(st&&st.snapshot&&st.snapshot!==D.snapshot) setTimeout(()=>flash('Plan was made on the '+st.snapshot+' snapshot; territory has changed since'),600);
}catch(e){ plan=[]; }
const gPlanClaim=new Uint8Array(N), gPlanBody=new Uint8Array(N);
function rebuildPlanGrids(){
  lodDirty=true;
  gPlanClaim.fill(0); gPlanBody.fill(0);
  plan.forEach(p=>{
    zoneTiles(p.x,p.y,p.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gPlanClaim[idx(x,y)]=1; });
    bodyTiles(p.x,p.y,p.fort).forEach(([x,y])=>{ if(inCrop(x,y)) gPlanBody[idx(x,y)]=1; });
  });
}
function zoneCovers(p,x,y){
  const b=zoneBoxUV(p.x,p.y,p.fort); const [u,v]=uv(x,y);
  return u>=b[0]&&u<=b[1]&&v>=b[2]&&v<=b[3];
}
const BAND=D.legalBand;
function inBand(x,y){ return x>=BAND.x0&&x<=BAND.x1&&y>=BAND.y0&&y<=BAND.y1; }
function fortsUsed(){ return S.filter(s=>s.owner===D.myAid&&s.fort).length + plan.filter(p=>p.fort).length; }
// mirrors NWorldAddingItem.UpdateGround's order per body tile
function validate(px,py,isFort){
  if(isFort && fortsUsed() >= D.live.maxForts)
    return {ok:false,reason:'alliance fort cap reached ('+D.live.maxForts+', incl. any under construction)'};
  for(const [x,y] of bodyTiles(px,py,isFort)){
    if(!inCrop(x,y)) return {ok:false,reason:'outside the mapped area'};
    const i=idx(x,y);
    if(gBlock[i]) return {ok:false,reason:'mountain / blocked terrain'};
    if(gBody[i]) return {ok:false,reason:'occupied by a structure'};
    if(gPlanBody[i]) return {ok:false,reason:'occupied by a planned structure'};
    if(gPlanClaim[i]) return {ok:false,reason:'inside a planned zone'};
    if(gRing[i]) continue;                       // own-gate ring: placeable
    if(gClaim[i]) return {ok:false,reason:tagOf(aidOfIdx[gClaim[i]])+' claimed tile'};
    if(gExcl[i]) return {ok:false,reason:'fixed-building zone'};
    // inside the wall corridor we probed the live client tile-by-tile, so its verdict
    // also applies: it catches bases/cities this static model cannot see
    if(inBand(x,y) && !gLegalV[i]) return {ok:false,reason:'blocked in game (base, city or unit on the tile)'};
  }
  return {ok:true};
}
let _pp=null;
function invalidatePP(){ _pp=null; }
function planPowered(){
  if(_pp) return _pp;
  const extras=plan.map(p=>({x:p.x,y:p.y,fort:p.fort,__p:p}));
  const m=powerOf(D.myAid,extras);
  _pp=new Map(); extras.forEach(e=>_pp.set(e.__p,m.get(e))); return _pp;
}

// ---- canvas ----
const cv=document.getElementById('cv'), ctx=cv.getContext('2d');
let zoom=1, ox=0, oy=0;
function resize(){ cv.width=cv.clientWidth*devicePixelRatio; cv.height=cv.clientHeight*devicePixelRatio; draw(); }
window.addEventListener('resize',resize);
const px=(x,y)=>[(x-X0)*TW/2,(y-Y0)*TH/2];
const scr=(wx,wy)=>[(wx-ox)*zoom*devicePixelRatio,(wy-oy)*zoom*devicePixelRatio];
let showClaims=true, showZones=true, showGrid=false, showMtn=true, showJump=true, showLegal=false, showBlock=false, showAreas=true;
// ---- low-zoom sheet: one pixel per tile (cell x, tile y), blitted onto the map rect
const LOD_Z=0.42, LODW=D.mask.cols, LODH=D.mask.rows;
const lod=document.createElement('canvas'); lod.width=LODW; lod.height=LODH;
let lodDirty=true;
const hex2rgb=(h)=>[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];
const CLRGB={}; Object.keys(CL).forEach(k=>CLRGB[k]=hex2rgb(CL[k]));
function buildLOD(){
  const g=lod.getContext('2d'), im=g.createImageData(LODW,LODH), d=im.data;
  for(let y=0;y<LODH;y++){
    const par=y&1;
    for(let c=0;c<LODW;c++){
      const x=c*2+par; if(!inCrop(x,y)) continue;
      const i=idx(x,y), o=(y*LODW+c)*4;
      if(gBlock[i]){ d[o]=38;d[o+1]=44;d[o+2]=54;d[o+3]=showMtn?(showBlock?190:0):235; continue; }
      if(showClaims&&gPlanClaim[i]){ d[o]=121;d[o+1]=192;d[o+2]=255;d[o+3]=190; continue; }
      if(showClaims&&gClaim[i]){ const c3=CLRGB[gClaim[i]]||[139,148,158];
        d[o]=c3[0];d[o+1]=c3[1];d[o+2]=c3[2];d[o+3]=170; continue; }
      if(showZones&&gExcl[i]){ d[o]=248;d[o+1]=81;d[o+2]=73;d[o+3]=60; }
    }
  }
  g.putImageData(im,0,0); lodDirty=false;
}
// ---- area (district) boundaries: segments in [cellX,row] units, row = tile y / 2
const ASEG=D.areas.segs, ALAB=D.areas.labels;
const AX=(c)=>c*TW, AY=(r)=>r*TH;              // 2 x-units = TW px, 2 rows = TH px
const AREA_NAME=(a,dom)=>{
  if(a===31) return 'Eternal City';
  if(a>=100) return '';
  if(a>=21) return 'Inner ring';
  if(a>=11) return 'Mid ring';
  return dom?('S'+dom):('sector '+a);
};
let tool='pan', hover=null;

function tilePath(x,y,scale){
  const [wx,wy]=px(x,y); const [sx,sy]=scr(wx,wy);
  const hw=TW/2*zoom*devicePixelRatio*(scale||1), hh=TH/2*zoom*devicePixelRatio*(scale||1);
  ctx.moveTo(sx,sy-hh); ctx.lineTo(sx+hw,sy); ctx.lineTo(sx,sy+hh); ctx.lineTo(sx-hw,sy); ctx.closePath();
}
function visRange(){
  const cssW=cv.clientWidth, cssH=cv.clientHeight;
  return [Math.max(X0,Math.floor(ox/(TW/2))+X0-2), Math.min(X1,Math.ceil((ox+cssW/zoom)/(TW/2))+X0+2),
          Math.max(Y0,Math.floor(oy/(TH/2))+Y0-2), Math.min(Y1,Math.ceil((oy+cssH/zoom)/(TH/2))+Y0+2)];
}
const ICON_SPEC = {ps:{w:1.7,cy:0,drop:.55}, fort:{w:2.6,cy:1,drop:1}, outpost:{w:2.3,cy:1,drop:1},
                   base:{w:2.6,cy:1,drop:1}, gate:{w:2.0,cy:1,drop:1.55}, mfort:{w:2.6,cy:1,drop:1},
                   research:{w:2.6,cy:1,drop:1}, city:{w:3.4,cy:2,drop:1.2}, ark:{w:3.0,cy:4,drop:1.4}};
function iconH(kind){
  const im=ICONS[kind], spec=ICON_SPEC[kind];
  if(!im||!im.complete||!im.naturalWidth) return TH*zoom*devicePixelRatio;
  return spec.w*TW*zoom*devicePixelRatio*im.naturalHeight/im.naturalWidth;
}
function drawIcon(kind,gx,gy,opts){
  opts=opts||{};
  const im=ICONS[kind], spec=ICON_SPEC[kind];
  const w=spec.w*TW*zoom*devicePixelRatio;
  if(!im||!im.complete||!im.naturalWidth||w<13) return false;
  const h=w*im.naturalHeight/im.naturalWidth;
  const [wx,wy]=px(gx,gy+spec.cy); const [sx,sy]=scr(wx,wy);
  ctx.save();
  if(opts.gray) ctx.filter='grayscale(70%)';
  ctx.globalAlpha=opts.alpha!==undefined?opts.alpha:1;
  ctx.drawImage(im,sx-w/2,sy+TH*zoom*devicePixelRatio*spec.drop-h,w,h);
  ctx.restore();
  return true;
}
let _raf=0;
function draw(){ if(_raf) return; _raf=requestAnimationFrame(()=>{_raf=0;render();}); }
function render(){
  ctx.clearRect(0,0,cv.width,cv.height);
  const [x0,x1,y0,y1]=visRange();
  // ---- terrain: the game's own render, placed 1:1 on the crop rect ----
  const kx=zoom*devicePixelRatio;
  if(showMtn){
    ctx.imageSmoothingEnabled=true; ctx.imageSmoothingQuality='high';
    // the district sheet is a different capture pass, so its tone differs slightly from
    // the world sheet; only bring it in once it is actually adding detail, otherwise it
    // reads as a bright rectangle over the overview
    ['world','district'].forEach(k=>{
      const t=TERR[k];
      if(!t.im.complete||!t.im.naturalWidth) return;
      if(k==='district'&&zoom<0.34) return;
      const [tx,ty]=scr(t.dx,t.dy);
      ctx.drawImage(t.im,tx,ty,t.dw*kx,t.dh*kx);
    });
  }
  // ---- claims + blocked ----
  // Per-tile diamonds are ~590k paths at whole-map zoom, so below LOD_Z we blit one
  // pre-rendered cell sheet (384x1536, one pixel per tile) scaled onto the same rect.
  if(zoom < LOD_Z){
    if(lodDirty) buildLOD();
    const [tx,ty]=scr(0,0);
    ctx.imageSmoothingEnabled=false;
    ctx.globalAlpha=showMtn?0.66:1;
    ctx.drawImage(lod,tx,ty,(X1-X0+1)*TW/2*kx,(Y1-Y0+1)*TH/2*kx);
    ctx.globalAlpha=1; ctx.imageSmoothingEnabled=true;
  } else
  for(let y=y0;y<=y1;y++){
    for(let x=x0+((x0+y)%2!==0?1:0); x<=x1; x+=2){
      const i=idx(x,y);
      // with the terrain art on the blocked mask is an optional overlay on top of the
      // real mountain; with the art off the mask *is* the terrain
      if(gBlock[i]){
        if(!showMtn){ ctx.fillStyle='#262c36'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
        else if(showBlock){ ctx.fillStyle='#0d1117aa'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
        continue;
      }
      if(showClaims&&gClaim[i]){ ctx.fillStyle=CL[gClaim[i]]+(showMtn?'55':'3d'); ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showClaims&&gPlanClaim[i]){ ctx.fillStyle='#79c0ff3d'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showZones&&gExcl[i]){ ctx.fillStyle='#f8514922'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showLegal&&gLegalV[i]&&!gClaim[i]){ ctx.fillStyle='#3fb95015'; ctx.beginPath(); tilePath(x,y,1); ctx.fill(); }
      if(showJump&&gJumpW[i]){ ctx.fillStyle='#79c0ff66'; ctx.beginPath(); tilePath(x,y,1); ctx.fill();
        ctx.strokeStyle='#79c0ff'; ctx.lineWidth=Math.max(1,.9*kx*.5); ctx.stroke(); }
      if(showJump&&gJump[i]){ ctx.fillStyle='#d2a8ff66'; ctx.beginPath(); tilePath(x,y,1); ctx.fill();
        ctx.strokeStyle='#d2a8ff'; ctx.lineWidth=Math.max(1,.9*kx*.5); ctx.stroke(); }
    }
  }
  if(showGrid&&zoom>1.4){
    ctx.strokeStyle='#ffffff10'; ctx.lineWidth=1; ctx.beginPath();
    for(let y=y0;y<=y1;y++) for(let x=x0+((x0+y)%2!==0?1:0); x<=x1; x+=2) tilePath(x,y,1);
    ctx.stroke();
  }
  // ---- area (district) boundaries straight from the client's own area map ----
  if(showAreas){
    ctx.strokeStyle='#e6edf344'; ctx.lineWidth=Math.max(1,1.1*kx*.5);
    ctx.beginPath();
    ASEG.forEach(([c0,r0,c1,r1])=>{
      const a=scr(AX(c0),AY(r0)), b=scr(AX(c1),AY(r1));
      if((a[0]<0&&b[0]<0)||(a[0]>cv.width&&b[0]>cv.width)||(a[1]<0&&b[1]<0)||(a[1]>cv.height&&b[1]>cv.height)) return;
      ctx.moveTo(a[0],a[1]); ctx.lineTo(b[0],b[1]);
    });
    ctx.stroke();
  }
  // at whole-map zoom the icons are too small to draw, so mark the forts
  if(zoom<LOD_Z){
    S.forEach(s=>{
      if(!s.fort) return;
      const [wx,wy]=px(s.x,s.y); const [sx,sy]=scr(wx,wy);
      if(sx<-8||sy<-8||sx>cv.width+8||sy>cv.height+8) return;
      ctx.beginPath(); ctx.arc(sx,sy,Math.max(2.2,3.4*kx),0,Math.PI*2);
      ctx.fillStyle=CL[AIDN[s.owner]]||'#8b949e'; ctx.fill();
      ctx.strokeStyle='#0d1117'; ctx.lineWidth=1; ctx.stroke();
    });
  }
  // ---- zone outlines for our own structures ----
  if(showClaims){
    S.forEach(s=>{
      if(s.owner!==D.myAid) return;
      if(s.x<x0-14||s.x>x1+14||s.y<y0-14||s.y>y1+14) return;
      const powered=powerByAid[s.owner]?powerByAid[s.owner].get(s):true;
      ctx.strokeStyle=CL[1]+(powered?'88':'44');
      ctx.lineWidth=1.2*zoom*devicePixelRatio*.5;
      strokeZone(s.x,s.y,s.fort);
    });
  }
  // ---- structures / fixed buildings / plan, depth-sorted north->south like the
  // game's units layer (terrain is the mosaic underneath, so nothing can paint over
  // a Gate any more) ----
  const kk=zoom*devicePixelRatio;
  const objItems=[];
  S.forEach(s=>{ if(s.x>=x0-14&&s.x<=x1+14&&s.y>=y0-14&&s.y<=y1+14) objItems.push(s); });
  FIX.forEach(f=>{ if(f.X>=x0-16&&f.X<=x1+16&&f.Y>=y0-16&&f.Y<=y1+16) objItems.push(f); });
  const pp=planPowered();
  plan.forEach((p,i)=>objItems.push({kind:'plan',p,i,depth:(p.y-Y0)*TH/2}));
  objItems.sort((a,b)=>a.depth-b.depth);
  const k=kk;
  objItems.forEach(it=>{
    if(it.kind==='struct'){
      const s=it, an=AIDN[s.owner], col=CL[an]||'#8b949e';
      const powered=powerByAid[s.owner]?powerByAid[s.owner].get(s):true;
      const building=s.st===2;
      ctx.beginPath(); bodyTiles(s.x,s.y,s.fort).forEach(([bx,by])=>tilePath(bx,by,0.92));
      ctx.fillStyle=col+(building?'44':'77'); ctx.fill();
      if(!powered&&!building){ ctx.strokeStyle='#f85149'; ctx.lineWidth=1.5*k*.5; ctx.stroke(); }
      drawIcon(s.fort?'fort':'ps', s.x, s.y, {alpha: building?.55:(powered?1:.5), gray: building});
      if(s.fort&&zoom>.8){
        const [wx,wy]=px(s.x,s.y+2); const [sx,sy]=scr(wx,wy);
        ctx.fillStyle='#fff'; ctx.font=`${9*k*.7}px sans-serif`; ctx.textAlign='center';
        ctx.fillText('FORT '+tagOf(s.owner)+(building?' (building)':''), sx, sy+TH*k*.9);
      }
    } else if(it.kind==='fixed'){
      const f=it;
      ctx.beginPath(); bodyTiles(f.X,f.Y,true).forEach(([bx,by])=>tilePath(bx,by,0.92));
      ctx.fillStyle=f.sid?'#3fb95055':'#6e768155'; ctx.fill();
      ctx.strokeStyle=f.sid?'#3fb950aa':'#f8514966'; ctx.lineWidth=1; ctx.stroke();
      drawIcon(FIXICON[f.bt]||'outpost', f.X, f.Y, {});
      if(zoom>.9){
        const [wx,wy]=px(f.X,f.Y+2); const [sx,sy]=scr(wx,wy);
        ctx.fillStyle='#e6edf3'; ctx.font=`${8.5*k*.7}px sans-serif`; ctx.textAlign='center';
        ctx.fillText(f.name+' '+f.X+';'+f.Y+(f.tag?' ['+f.tag+']':''), sx, sy+TH*k*1.3);
      }
    } else if(it.kind==='plan'){
      const p=it.p;
      ctx.beginPath(); bodyTiles(p.x,p.y,p.fort).forEach(([bx,by])=>tilePath(bx,by,0.95));
      const stCol=pp.get(p)?'#3fb950':'#d29922';
      ctx.fillStyle='#79c0ff44'; ctx.fill();
      ctx.strokeStyle=stCol; ctx.lineWidth=2*k*.5; ctx.stroke();
      ctx.strokeStyle='#79c0ff66'; ctx.lineWidth=1; strokeZone(p.x,p.y,p.fort);
      drawIcon(p.fort?'fort':'ps', p.x, p.y, {alpha:.92});
      if(zoom>.9){
        const [wx,wy]=px(p.x,p.y); const [sx,sy]=scr(wx,wy);
        ctx.fillStyle=stCol; ctx.font=`bold ${9.5*k*.7}px sans-serif`; ctx.textAlign='center';
        ctx.fillText('#'+(it.i+1), sx, sy-iconH(p.fort?'fort':'ps'));
      }
    }
  });
  // ---- jump callouts: west spot -> east landing, on top of everything ----
  if(showJump){
    const S2=(gx,gy)=>{ const [wx,wy]=px(gx,gy); return scr(wx,wy); };
    // every pair, faint, so the whole corridor reads at a glance
    ctx.save(); ctx.setLineDash([4*k*.5,4*k*.5]); ctx.lineWidth=1.1*k*.5; ctx.strokeStyle='#79c0ff55';
    JUMPS.forEach(c=>(c.pairs||[]).forEach(([wx2,wy2,ex,ey])=>{
      if(ey<y0-24||ey>y1+24) return;
      const a=S2(wx2,wy2), b=S2(ex,ey);
      ctx.beginPath(); ctx.moveTo(a[0],a[1]); ctx.lineTo(b[0],b[1]); ctx.stroke();
    }));
    ctx.restore();
    JUMPS.forEach((c,ci)=>{
      const [bx,by]=c.best;
      if(bx<x0-24||bx>x1+24||by<y0-24||by>y1+24) return;
      const [sx,sy]=S2(bx,by);
      if(c.bestWest){
        const [asx,asy]=S2(c.bestWest[0],c.bestWest[1]);
        ctx.save();
        if(c.westKind==='new') ctx.setLineDash([6*k*.5,4*k*.5]);
        ctx.strokeStyle=c.westKind==='new'?'#79c0ffee':'#d2a8ffcc'; ctx.lineWidth=2*k*.5;
        ctx.beginPath(); ctx.moveTo(asx,asy); ctx.lineTo(sx,sy); ctx.stroke(); ctx.restore();
        // west marker
        ctx.beginPath(); ctx.arc(asx,asy,5*k*.6,0,Math.PI*2);
        ctx.fillStyle=c.westKind==='new'?'#79c0ff':'#3fb950'; ctx.fill();
        ctx.strokeStyle='#0d1117'; ctx.lineWidth=1.2*k*.4; ctx.stroke();
        if(zoom>.7){
          ctx.fillStyle=c.westKind==='new'?'#79c0ff':'#3fb950'; ctx.font=`bold ${9*k*.7}px sans-serif`; ctx.textAlign='center';
          ctx.fillText((c.westKind==='new'?'NEW PS ':'PS ')+c.bestWest[0]+';'+c.bestWest[1], asx, asy-8*k*.7);
        }
      }
      // east marker
      ctx.beginPath(); ctx.arc(sx,sy,5.5*k*.6,0,Math.PI*2);
      ctx.fillStyle='#d2a8ff'; ctx.fill();
      ctx.fillStyle='#0d1117'; ctx.font=`bold ${8*k*.6}px sans-serif`; ctx.textAlign='center'; ctx.textBaseline='middle';
      ctx.fillText(String(ci+1), sx, sy);
      ctx.textBaseline='alphabetic';
      if(zoom>.7){
        ctx.fillStyle='#d2a8ff'; ctx.font=`bold ${9.5*k*.7}px sans-serif`;
        ctx.fillText('LAND '+bx+';'+by, sx, sy-9*k*.7);
      }
    });
  }
  // ---- area labels, always legible, on top ----
  if(showAreas){
    ctx.textAlign='center'; ctx.textBaseline='middle';
    ALAB.forEach(([a,cx,cy,tiles,dom,structs])=>{
      const nm=AREA_NAME(a,dom); if(!nm) return;
      const [sx,sy]=scr(AX(cx),AY(cy));
      if(sx<-60||sy<-20||sx>cv.width+60||sy>cv.height+20) return;
      const big=a===31, f=(big?13:11.5)*devicePixelRatio;
      ctx.font=`600 ${f}px sans-serif`;
      ctx.lineWidth=3*devicePixelRatio; ctx.strokeStyle='#0d1117cc';
      ctx.strokeText(nm,sx,sy); ctx.fillStyle=big?'#ffdf5d':'#e6edf3bb'; ctx.fillText(nm,sx,sy);
      if(structs&&zoom>0.16){
        ctx.font=`${9.5*devicePixelRatio}px sans-serif`;
        ctx.strokeText(structs+' structures',sx,sy+f+2*devicePixelRatio);
        ctx.fillStyle='#8b949e'; ctx.fillText(structs+' structures',sx,sy+f+2*devicePixelRatio);
      }
    });
    ctx.textBaseline='alphabetic'; ctx.textAlign='left';
  }
  // ---- ghost ----
  if((tool==='ps'||tool==='fort')&&hover){
    const isFort=tool==='fort';
    const chk=validate(hover[0],hover[1],isFort);
    let color='#3fb950';
    if(!chk.ok) color='#f85149';
    else{
      const extras=plan.map(p=>({x:p.x,y:p.y,fort:p.fort})).concat([{x:hover[0],y:hover[1],fort:isFort}]);
      if(!powerOf(D.myAid,extras).get(extras[extras.length-1])) color='#d29922';
    }
    ctx.globalAlpha=.85;
    ctx.beginPath(); bodyTiles(hover[0],hover[1],isFort).forEach(([bx,by])=>tilePath(bx,by,0.95));
    ctx.fillStyle=color+'55'; ctx.fill(); ctx.strokeStyle=color; ctx.lineWidth=2; ctx.stroke();
    ctx.strokeStyle=color+'99'; ctx.lineWidth=1.4; strokeZone(hover[0],hover[1],isFort);
    ctx.globalAlpha=1;
    drawIcon(isFort?'fort':'ps',hover[0],hover[1],{alpha:.7});
  }
}
function strokeZone(x,y,isFort){
  // true zone boundary: outer edge of the corner tiles, not their centres
  const b=zoneBoxUV(x,y,isFort);
  const c=[xy(b[0],b[2]),xy(b[1],b[2]),xy(b[1],b[3]),xy(b[0],b[3])];
  const hw=TW/2*zoom*devicePixelRatio, hh=TH/2*zoom*devicePixelRatio;
  const off=[[0,-hh],[hw,0],[0,hh],[-hw,0]];
  ctx.beginPath();
  c.forEach((t,i)=>{
    const [wx,wy]=px(t[0],t[1]); const [sx,sy]=scr(wx,wy);
    const p=[sx+off[i][0],sy+off[i][1]];
    i?ctx.lineTo(p[0],p[1]):ctx.moveTo(p[0],p[1]);
  });
  ctx.closePath(); ctx.stroke();
}

// ---- interaction ----
let dragging=false,lx=0,ly=0,moved=false;
cv.addEventListener('mousedown',e=>{dragging=true;moved=false;lx=e.clientX;ly=e.clientY;});
window.addEventListener('mouseup',()=>{
  if(dragging&&!moved&&(tool==='ps'||tool==='fort')&&hover){
    const isFort=tool==='fort';
    const chk=validate(hover[0],hover[1],isFort);
    if(chk.ok){
      plan.push({x:hover[0],y:hover[1],fort:isFort});
      savePlan(); rebuildPlanGrids(); invalidatePP(); renderPlan(); draw();
    } else flash('Cannot place: '+chk.reason);
  }
  dragging=false;
});
cv.addEventListener('mousemove',e=>{
  const r=cv.getBoundingClientRect();
  if(dragging){
    const dx=e.clientX-lx, dy=e.clientY-ly;
    if(Math.abs(dx)+Math.abs(dy)>3) moved=true;
    ox-=dx/zoom; oy-=dy/zoom; lx=e.clientX; ly=e.clientY; draw();
  }
  const wx=(e.clientX-r.left)/zoom+ox, wy=(e.clientY-r.top)/zoom+oy;
  const gx=Math.round(wx/(TW/2))+X0, gy=Math.round(wy/(TH/2))+Y0;
  let best=null,bd=1e9;
  for(let cx=gx-2;cx<=gx+2;cx++)for(let cy=gy-1;cy<=gy+1;cy++){
    if(((cx%2+2)%2)!==((cy%2+2)%2)) continue;
    const [twx,twy]=px(cx,cy); const d=(twx-wx)**2+((twy-wy)*(TW/TH))**2;
    if(d<bd){bd=d;best=[cx,cy];}
  }
  hover=best;
  document.getElementById('coord').textContent = best? best[0]+';'+best[1] : '-';
  updateTip(e,best);
  if(tool!=='pan'||dragging) draw();
});
cv.addEventListener('wheel',e=>{
  e.preventDefault();
  const r=cv.getBoundingClientRect();
  const mx=e.clientX-r.left, my=e.clientY-r.top;
  const wx=mx/zoom+ox, wy=my/zoom+oy;
  zoom*=e.deltaY<0?1.15:0.87; zoom=Math.max(.3,Math.min(8,zoom));
  ox=wx-mx/zoom; oy=wy-my/zoom; draw();
},{passive:false});

function updateTip(e,t){
  const tip=document.getElementById('tip');
  if(!t){tip.style.display='none';return;}
  const i=inCrop(t[0],t[1])?idx(t[0],t[1]):-1;
  const bits=[];
  const s=S.find(s=>bodyTiles(s.x,s.y,s.fort).some(([bx,by])=>bx===t[0]&&by===t[1]));
  if(s){
    const powered=powerByAid[s.owner]?powerByAid[s.owner].get(s):true;
    bits.push(`<b>${s.fort?'Alliance Fort':'Power Station'}</b> &middot; ${tagOf(s.owner)} <span style="color:#8b949e">S${ASRV[s.owner]||'?'}</span> &middot; ${s.st===2?'under construction':'built'}`
      + (s.st===3?(powered?' &middot; powered':' &middot; <span style="color:#f85149">NO POWER (predicted)</span>'):'') + ` &middot; ${s.x};${s.y}`);
  }
  const f=FIX.find(f=>bodyTiles(f.X,f.Y,true).some(([bx,by])=>bx===t[0]&&by===t[1]));
  if(f) bits.push(`<b>${f.name}</b> ${f.X};${f.Y} &middot; ${f.tag?('held by '+f.tag):'unowned'}`);
  if(i>=0){
    if(gJump[i]) bits.push('<span style="color:#d2a8ff">wall-jump landing tile</span>');
    if(gBlock[i]) bits.push('Blocked terrain');
    if(gExcl[i]) bits.push('Fixed-building zone (no build)');
    if(gClaim[i]) bits.push(tagOf(aidOfIdx[gClaim[i]])+' territory');
    if(gPlanClaim[i]) bits.push('Planned zone');
    if(gLegalV[i]&&!gClaim[i]&&!gBlock[i]) bits.push('<span style="color:#3fb950">verified placeable in game</span>');
  }
  if(!bits.length){tip.style.display='none';return;}
  tip.innerHTML=bits.join('<br>');
  tip.style.display='block';
  tip.style.left=Math.min(e.clientX+14, innerWidth-270)+'px';
  tip.style.top=(e.clientY+14)+'px';
}
let flashT=null;
function flash(msg){
  const tip=document.getElementById('tip');
  tip.innerHTML='<span style="color:#f85149">'+msg+'</span>';
  tip.style.display='block';
  clearTimeout(flashT); flashT=setTimeout(()=>tip.style.display='none',2000);
}

// ---- side panel ----
function counts(){
  const c=new Array(D.alliances.length+1).fill(0);
  for(let i=0;i<N;i++) if(gClaim[i]) c[gClaim[i]]++;
  const mine=S.filter(s=>s.owner===D.myAid);
  const built=mine.filter(s=>!s.fort&&s.st===3);
  const act=built.filter(s=>powerByAid[D.myAid].get(s));
  const tiles=(tag)=>{ const a=Object.keys(TAG).find(k=>TAG[k]===tag); return a?c[AIDN[a]].toLocaleString():'-'; };
  document.getElementById('sDog').textContent=tiles('Dog*');
  document.getElementById('sMss').textContent=tiles('MSS*');
  document.getElementById('sCat').textContent=tiles('Cat+');
  renderWorld(c);
  document.getElementById('sAct').textContent=act.length+' / '+built.length;
  document.getElementById('sBld').textContent=mine.filter(s=>s.st===2).length;
  document.getElementById('sFort').textContent=fortsUsed()+' / '+D.live.maxForts;
  const cap=D.live.psCapBase+D.live.psCapBuff;
  document.getElementById('sPsCap').textContent=D.live.psBuilt+' / '+cap;
  const okRank=D.live.psJurisdiction.split(';').indexOf(String(D.live.rank))>=0;
  const el=document.getElementById('sRank');
  el.textContent='rank '+D.live.rank+(okRank?' can build':' CANNOT build');
  el.style.color=okRank?'var(--green)':'var(--red)';
}
// ---- whole-map panels: warzones, objectives, navigation ----
const OBJ_NAME={3:'Expedition Outpost',4:'Expedition Base',5:'Arsenal / Military Base',
                6:'Military Fortress',7:'Research Facility',8:'Eternal City',9:'Gate',10:'Molten Ark'};
function renderWorld(claimCounts){
  // per-server rollup
  const srv={};
  S.forEach(s=>{
    const sid=ASRV[s.owner]||0;
    const r=srv[sid]||(srv[sid]={ps:0,fort:0,tiles:0,tags:new Set()});
    s.fort?r.fort++:r.ps++; r.tags.add(tagOf(s.owner));
  });
  D.alliances.forEach((a,i)=>{ const sid=a[3]; if(srv[sid]) srv[sid].tiles+=claimCounts[i+1]||0; });
  const rows=Object.keys(srv).map(k=>[+k,srv[k]]).sort((a,b)=>(b[1].ps+b[1].fort)-(a[1].ps+a[1].fort));
  const el=document.getElementById('srvTable'); el.innerHTML='';
  rows.forEach(([sid,r])=>{
    const div=document.createElement('div'); div.className='stat';
    const mine=sid===2864;
    div.innerHTML=`<span><span class="sw" style="background:${D.srvColor[sid]||'#8b949e'};border-color:${D.srvColor[sid]||'#8b949e'}"></span>`
      +`<b style="${mine?'color:var(--green)':''}">S${sid}</b> <span style="color:var(--muted)">${[...r.tags].sort().join(' ')}</span></span>`
      +`<b>${r.ps+r.fort} <span style="color:var(--muted);font-weight:400">(${r.fort}f)</span></b>`;
    el.appendChild(div);
  });
  document.getElementById('srvNote').innerHTML=
    `${S.length.toLocaleString()} structures, ${D.alliances.length} alliances, ${rows.length} warzones &mdash; harvested from 159 camera stops across the whole map. `
    +`Ours is <b style="color:var(--green)">S2864</b>. Other servers' per-alliance splits are live from the same sweep; only S2864's power state is authoritative.`;
  // objectives
  const ot=document.getElementById('objTable'); ot.innerHTML='';
  const byType={};
  FIX.forEach(f=>{ const t=byType[f.bt]||(byType[f.bt]={n:0,owned:0}); t.n++; if(f.sid) t.owned++; });
  Object.keys(byType).sort((a,b)=>a-b).forEach(bt=>{
    const t=byType[bt], div=document.createElement('div'); div.className='stat';
    div.innerHTML=`<span>${OBJ_NAME[bt]||('type '+bt)}</span>`
      +`<b>${t.owned?`<span class="ok">${t.owned}</span>`:'<span class="warn">0</span>'} / ${t.n}</b>`;
    ot.appendChild(div);
  });
}
function buildNav(){
  const sel=document.getElementById('nav');
  const opts=[['','Jump to…'],['home','Our home (Dog*)']];
  ALAB.slice().sort((a,b)=>b[5]-a[5]).forEach(([a,cx,cy,tiles,dom,structs])=>{
    const nm=AREA_NAME(a,dom); if(!nm) return;
    opts.push(['a'+a, (a===31?'':(a<11?'Warzone ':'')) + nm + (structs?` (${structs})`:'') ]);
  });
  FIX.filter(f=>[5,6,7,8,10].indexOf(f.bt)>=0).sort((a,b)=>a.bt-b.bt).forEach(f=>
    opts.push(['f'+f.X+','+f.Y, f.name+' '+f.X+';'+f.Y]));
  sel.innerHTML=opts.map(([v,t])=>`<option value="${v}">${t}</option>`).join('');
  sel.onchange=()=>{
    const v=sel.value; if(!v) return;
    if(v==='home'){ flyTo(60,1000,1.1); }
    else if(v[0]==='a'){ const a=ALAB.find(l=>l[0]===+v.slice(1));
      if(a) flyTo(Math.round(a[1]*2), Math.round(a[2]*2), a[0]===31?0.9:0.5); }
    else if(v[0]==='f'){ const [x,y]=v.slice(1).split(',').map(Number); flyTo(x,y,1.6); }
    sel.value='';
  };
}
function renderPlan(){
  const el=document.getElementById('plan'); el.innerHTML='';
  const pp=planPowered();
  let tiles=0,cost=0,time=0;
  const claimed=new Set();
  for(let i=0;i<N;i++) if(gClaim[i]) claimed.add(i);   // mountains inside a zone ARE claimed
  plan.forEach((p,i)=>{
    zoneTiles(p.x,p.y,p.fort).forEach(([x,y])=>{ if(inCrop(x,y)){const j=idx(x,y); if(!claimed.has(j)){claimed.add(j);tiles++;}} });
    cost+=p.fort?10000:500; time+=p.fort?3:2;
    const div=document.createElement('div'); div.className='planitem';
    div.innerHTML=`<span>#${i+1} ${p.fort?'Fort':'PS'} @ <b>${p.x};${p.y}</b> <span class="${pp.get(p)?'ok':'warn'}">${pp.get(p)?'powered':'no power (predicted)'}</span></span><span class="del" data-i="${i}">&times;</span>`;
    el.appendChild(div);
  });
  document.getElementById('pTiles').textContent=tiles.toLocaleString();
  document.getElementById('pCost').textContent=cost.toLocaleString();
  document.getElementById('pTime').textContent=time+'h';
  document.getElementById('planEmpty').style.display=plan.length?'none':'block';
  el.querySelectorAll('.del').forEach(d=>d.onclick=()=>{plan.splice(+d.dataset.i,1);savePlan();rebuildPlanGrids();invalidatePP();renderPlan();draw();});
  counts();
}
function renderJumps(){
  const el=document.getElementById('jumps'); el.innerHTML='';
  if(!JUMPS.length){ el.innerHTML='<div class="note">No gate-reachable crossing in this snapshot.</div>'; return; }
  JUMPS.forEach((c,i)=>{
    const div=document.createElement('div'); div.className='jrow';
    const wk=c.westKind==='new'
      ? `<span class="warn">place a NEW PS at ${c.bestWest[0]};${c.bestWest[1]}</span>`
      : `from <b>${c.bestAnchor}</b>`;
    div.innerHTML=`<div class="t">${i+1}. y ${c.y0}&ndash;${c.y1} &middot; land ${c.best[0]};${c.best[1]}</div>`
      +`<div class="d">${wk}<br>`
      +`${c.tiles} landing tiles &middot; ${c.west.length} west spots &middot; wall x${c.wall[0]}&ndash;${c.wall[1]} (${c.thick} thick)<br>`
      +`gate ${c.gate[0]};${c.gate[1]} (${c.gateSteps} steps from the landing tile)</div>`;
    div.onclick=()=>flyTo(Math.round((c.best[0]+(c.bestWest?c.bestWest[0]:c.best[0]))/2),c.best[1],2.2);
    el.appendChild(div);
  });
  (D.jumps.gateNotes||[]).forEach(n=>{
    const div=document.createElement('div'); div.className='jrow';
    div.style.opacity=.75;
    div.innerHTML=`<div class="t">Gate ${n.gate[0]};${n.gate[1]} &middot; <span class="warn">no crossing for us</span></div>`
      +`<div class="d">${n.why}${n.westClaimedBy.length?' &mdash; '+n.westClaimedBy.map(o=>o[0]+' holds '+o[1]+' of the west tiles').join(', '):''}</div>`;
    div.onclick=()=>flyTo(n.gate[0],n.gate[1],2.0);
    el.appendChild(div);
  });
}
function flyTo(x,y,z){
  zoom=z||2.2;
  const [wx,wy]=px(x,y);
  ox=wx-cv.clientWidth/2/zoom; oy=wy-cv.clientHeight/2/zoom;
  draw();
}
function savePlan(){ localStorage.setItem('elSimPlan4',JSON.stringify({snapshot:D.snapshot,items:plan})); }
function setTool(t){
  tool=t;
  document.getElementById('toolPan').classList.toggle('active',t==='pan');
  document.getElementById('toolPS').classList.toggle('active',t==='ps');
  document.getElementById('toolFort').classList.toggle('active',t==='fort');
  cv.classList.toggle('placing',t!=='pan');
}
document.getElementById('toolPan').onclick=()=>setTool('pan');
document.getElementById('toolPS').onclick=()=>setTool('ps');
document.getElementById('toolFort').onclick=()=>setTool('fort');
function tg(id,fn,on){
  const b=document.getElementById(id);
  if(on) b.classList.add('active');
  b.onclick=()=>{ b.classList.toggle('active'); fn(b.classList.contains('active')); lodDirty=true; draw(); };
}
tg('tgJump',v=>showJump=v,true);
tg('tgClaims',v=>showClaims=v,true);
tg('tgZones',v=>showZones=v,true);
tg('tgMtn',v=>showMtn=v,true);
tg('tgBlock',v=>showBlock=v,false);
tg('tgAreas',v=>showAreas=v,true);
tg('tgLegal',v=>showLegal=v,false);
tg('tgGridL',v=>showGrid=v,false);
document.getElementById('fit').onclick=fit;
document.getElementById('clearPlan').onclick=()=>{ if(plan.length&&confirm('Clear the whole plan?')){plan=[];savePlan();rebuildPlanGrids();invalidatePP();renderPlan();draw();} };
document.getElementById('copyPlan').onclick=()=>{
  const pp=planPowered();
  const lines=plan.map((p,i)=>`#${i+1} ${p.fort?'Alliance Fort':'Power Station'} @ ${p.x};${p.y}${pp.get(p)?'':' (WARNING: not connected to the fort chain)'}`);
  navigator.clipboard.writeText('EL build plan - snapshot '+D.snapshot+'\n'+lines.join('\n')).then(()=>flash('Plan copied'));
};
function fit(){
  const cssW=cv.clientWidth, cssH=cv.clientHeight;
  const wpx=W*TW/2, hpx=H*TH/2;
  zoom=Math.min(cssW/wpx,cssH/hpx)*0.96;
  ox=-(cssW/zoom-wpx)/2; oy=-(cssH/zoom-hpx)/2;
  draw();
}
// ---- self test: does the captured terrain line up with the blocked-tile mask? ----
window.__st = function(){
  const out={corridors:JUMPS.length, east:0, west:0, needNewPS:0,
             forts:fortsUsed()+'/'+D.live.maxForts,
             structs:S.length, fixed:FIX.length, alliances:D.alliances.length,
             blocked:0, terrain:{world:!!TERR.world.im.naturalWidth, district:!!TERR.district.im.naturalWidth}};
  for(let i=0;i<N;i++) if(gBlock[i]) out.blocked++;
  JUMPS.forEach(c=>{ out.east+=c.east.length; out.west+=c.west.length; if(c.needsNewPS) out.needNewPS++; });
  let bad=0, badW=0;
  JUMPS.forEach(c=>{
    c.east.forEach(([x,y])=>{ if(!validate(x,y,false).ok) bad++; });
    c.west.forEach(([x,y])=>{ if(!validate(x,y,false).ok) badW++; });
  });
  out.eastFailing=bad; out.westFailing=badW;
  out.texExample = JUMPS.some(c=>c.east.some(([x,y])=>x===133&&y===791)) ? 'OK' : 'MISSING';
  // per-server rollup, so the whole-map harvest can be checked at a glance
  const srv={};
  S.forEach(s=>{ const k='S'+(ASRV[s.owner]||0); srv[k]=(srv[k]||0)+1; });
  out.byServer=srv;
  // does the captured terrain sit where the blocked mask says? (home district sheet;
  // rock art is desaturated, grass is not - saturation is the discriminator)
  const T=TERR.district;
  if(T.im.naturalWidth){
    const c=document.createElement('canvas'); c.width=T.w; c.height=T.h;
    const g=c.getContext('2d'); g.drawImage(T.im,0,0);
    const mx0=Math.floor(108*112/T.wpp), mw=Math.ceil(42*112/T.wpp);
    const im=g.getImageData(mx0,0,mw,T.h).data;
    const rockAt=(x,y)=>{
      const mx=Math.round(x*112/T.wpp)-mx0, my=Math.round((y-750)*81/T.wpp);
      if(mx<0||mx>=mw||my<0||my>=T.h) return null;
      const i=(my*mw+mx)*4, r=im[i], gg=im[i+1], b=im[i+2];
      return (Math.max(r,gg,b)-Math.min(r,gg,b)) < 75;
    };
    const score=(dx,dy)=>{
      let hit=0,miss=0,fp=0,open=0;
      for(let y=756;y<=1324;y++) for(let x=112;x<=148;x++){
        if((x+y)%2) continue;
        const r=rockAt(x,y); if(r===null) continue;
        const j=idx(x+dx,y+dy); if(j<0||j>=N) continue;
        if(gBlock[j]){ r?hit++:miss++; } else { r?fp++:open++; }
      }
      return {onRock:+(hit/(hit+miss)*100).toFixed(1), falseRock:+(fp/(fp+open)*100).toFixed(1)};
    };
    out.mask = {aligned: score(0,0), shiftX_minus4: score(-4,0), shiftX_plus4: score(4,0),
                shiftY_minus4: score(0,-4), shiftY_plus4: score(0,4)};
  }
  return out;
};
rebuildPlanGrids(); renderJumps(); buildNav(); renderPlan(); resize(); fit(); setTool('pan');

window.__el = {flyTo:flyTo, fit:fit, render:render, D:D, S:S, FIX:FIX, JUMPS:JUMPS, TERR:TERR, validate:validate, selftest:window.__st};
})();
